import Link from "next/link";
import PolicyPage from "../components/PolicyPage";
import { buildMetadata } from "../seo";

export const metadata = buildMetadata({ title: "Before You Travel | Journey Support", description: "Travel preparation, insurance, passports, visas, partner selection and 24/7 in-travel support for Ryravel journeys.", path: "/travel-information" });

export default function TravelInformationPage() {
  return <PolicyPage title="The practical side of going far." intro="A private journey is easier to enjoy when preparation and support are clear before departure." updated="25 September 2026">
    <section><h2>Support while travelling</h2><p>Ryravel provides 24/7 in-travel support by email and direct call. We share the relevant contact details with your confirmed travel documents. Tell us promptly about a missed connection, supplier problem, health concern or material change so we can help coordinate the next step with local partners.</p></section>
    <section><h2>Flights and visa assistance</h2><p>International flights and visa fees are not included in the published journey price. Ryravel can quote flight booking and visa assistance as optional add-ons after learning your departure country and route. We will show the price and the scope of help before you choose either service. Airfares, ticket conditions and entry rules may change; a visa or entry decision is made by the relevant authority, not by Ryravel.</p><p>Travellers remain responsible for ensuring their passports, entry permission or visas, transit documents and health requirements are valid for the complete itinerary. Check official destination and transit guidance before booking and again before departure.</p></section>
    <section><h2>Insurance</h2><p>Personal travel insurance is not included in the published journey price unless the written proposal expressly says otherwise. We can quote suitable cover as a separate optional add-on where available for your residence and itinerary. Review the insurer, benefits, exclusions, coverage limits and claims process before deciding. You remain responsible for choosing insurance suitable for your circumstances, including medical care, evacuation, cancellation and interruption where appropriate.</p></section>
    <section><h2>Properties and local partners</h2><p>We select properties and local partners for suitability to your specific brief and emotional arc, considering location, character, service and the experience you request. A beautiful property that does not fit the purpose of the journey does not make the list. Your proposal names the arrangements being offered and notes what remains subject to availability. If a supplier must change before or during travel, we tell you promptly, explain the material difference and available alternatives or remedies, and seek your approval before a replacement is made, except where immediate action is necessary for safety.</p></section>
    <section><h2>Accessibility and personal needs</h2><p>Tell us early about mobility, dietary or other needs that affect the journey. We will check with the relevant suppliers and explain what can be accommodated before confirmation. Never assume a remote property or activity is accessible without written confirmation.</p></section>
    <section><h2>Before you commit</h2><p>A written proposal details the itinerary, inclusions, exclusions, payment dates and any supplier-specific conditions. Read our <Link href="/terms">booking terms</Link> and <Link href="/cancellations">cancellation policy</Link>, then ask us to clarify anything before you pay.</p></section>
  </PolicyPage>;
}
