export const caseStudies = [
  {
    number: "01",
    slug: "she-stopped-apologizing-for-needing-to-stop",
    headline: "She stopped apologizing for needing to stop.",
    seoTitle: "A Solo Restoration Journey in Zanzibar",
    description: "How a private six-night Zanzibar journey helped an exhausted traveller stop performing recovery and return with a boundary she could keep.",
    arc: "Exhausted, The Restoration",
    traveller: "Amara · Solo",
    destination: "Zanzibar, Tanzania",
    dates: "Six nights",
    returnLabel: "Permission and a boundary",
    image: "/journeys/ex9/exhausted-zanzibar-coast.webp",
    imageAlt: "A quiet stretch of Zanzibar coastline",
    theme: "coast",
    relatedJourney: "/journeys/exhausted",
    relatedLabel: "Explore restoration journeys",
    intro: "For two years, Amara woke up already tired. Six nights in Zanzibar did not overhaul her life. They helped her draw one line she had never let herself draw before.",
    designedAround: "Fewer decisions. Protected empty time. A single coastal rhythm. Human care without intrusion.",
    sections: [
      { label: "01 · Before", title: "She was not looking for a vacation.", paragraphs: [
        "For two years, Amara woke up already tired. Not the kind of tired sleep fixes. The kind that sits behind the eyes.",
        "She was building a career she had worked hard for, saying yes to everything because saying no felt like proof she could not handle it. Early starts became late replies. Her phone was in her hand before her feet touched the floor.",
        "Nothing was landing anymore—not dinner with people she loved, a small win at work or a weekend off. She was not simply exhausted. She felt estranged from the person who used to feel things fully.",
        "There was no dramatic breaking point. Just the slow accumulation of nights spent scrolling instead of sleeping. She had tried vacations. They changed the light, not the life waiting underneath it.",
      ], pullQuote: "A different destination was not enough. The journey itself had to ask less of her." },
      { label: "02 · The brief", title: "Nothing should be asked of her.", paragraphs: [
        "The idea that stopped her was not an itinerary. It was permission. After years of proving she could handle more, Ryravel would design six private nights in Zanzibar in which she did not have to perform capability, enthusiasm or even recovery.",
        "Her hesitation was the investment. Could she justify a bespoke journey with no crowded checklist to explain the cost to anyone else? She went anyway.",
      ] },
      { label: "03 · The turning point", title: "A morning asked nothing of her.", paragraphs: [
        "There was no grand breakthrough. What she remembers is smaller, and more important.",
        "One morning, Amara woke up and realized no one needed anything from her—not an email, a decision or a version of herself performing okay. She did not journal or optimize the day. She let the morning happen instead of managing it.",
        "Later, she noticed she had not checked her phone in four hours. Not because it had been taken away, but because she had forgotten it existed. Nothing had gone wrong in her absence.",
      ] },
      { label: "04 · The Return", title: "The change was a line she could keep.", paragraphs: [
        "Amara did not come home with a new personality or a dramatic life overhaul. She came home and drew one boundary she had never allowed herself before: no work email after 7 pm.",
        "She did not announce it as a policy. She simply began closing the door each evening, on purpose. Then she took days off without arranging them around a deadline. The change showed up in what she stopped doing—not in what she needed to announce.",
      ] },
    ],
    quote: "Maryangel, thank you for designing this trip for me.",
    quoteBy: "Amara · Exhausted, The Restoration",
    privacy: "“Amara” is a pseudonym. Her name and identifying details have been withheld at the traveller's request.",
  },
  {
    number: "02",
    slug: "family-journey-egypt-morocco",
    headline: "He had taken his family on vacation before. He had never taken them on a trip.",
    seoTitle: "A Bespoke Family Journey Through Egypt and Morocco",
    description: "A private family journey through Egypt and Morocco designed to help an overextended executive become present with his wife and four children.",
    arc: "Exhausted, The Restoration · Family Journey",
    traveller: "Richard · Family of six",
    destination: "Egypt and Morocco",
    dates: "27 July–2 August",
    returnLabel: "Presence without performance",
    theme: "sand",
    relatedJourney: "/journeys/exhausted",
    relatedLabel: "Explore restoration journeys",
    intro: "Richard had travelled with his family before. What he had never done was arrive without managing the experience from beginning to end.",
    designedAround: "Fewer decisions. Unstructured mornings. Meals without performance. Space for his wife to be seen and his children to be bored beside him.",
    sections: [
      { label: "01 · Before", title: "He was present in every room except theirs.", paragraphs: [
        "Richard had four children, a wife he loved and a job that owned his mornings before they began. For fifteen years, he had risen through one of Nigeria's largest oil and gas corporations. The work lived in his phone, in the tension between his shoulder blades and in the way he answered “I'm fine” before anyone asked.",
        "He had taken his family to Dubai, London and Accra. But a change of geography never changed what he brought with him: the need to manage the itinerary, the children's behaviour, his wife's experience and his own inability to be still.",
        "By July, his wife had stopped asking for his attention. His children had learned to perform happiness around him, the same way he performed relaxation. The house was full of people who had adapted to his absence while he was sitting right there.",
      ], pullQuote: "A different destination was not enough. The journey had to ask less of him, not more." },
      { label: "02 · The brief", title: "Nothing asked him to be the executive—or the perfect father.", paragraphs: [
        "Richard booked six nights across Egypt and Morocco around one principle: nothing asked him to prove that he was providing. His hesitation was the children. Would they be bored without scheduled entertainment? Would his wife have to pick up the slack? Would he spend another family holiday mentally negotiating production targets?",
        "He went because his wife had said, quietly, “I want to know you again. And I want them to know you.”",
      ] },
      { label: "03 · The turning point", title: "The morning had no agenda.", paragraphs: [
        "In Morocco, on the third day, Richard woke to find his children arguing about something trivial on the terrace and his wife reading. Nobody needed him to fix, plan or produce a memorable experience. He sat down and did nothing.",
        "His youngest climbed into his lap and fell asleep against his chest. Richard did not check his phone or calculate how much time it was taking. Later, he played a game with the children that had no point. They lost track of the score. His wife looked at him across the room in a way he had not seen in years.",
      ] },
      { label: "04 · The Return", title: "His presence became enough.", paragraphs: [
        "Richard came home and stopped checking his phone before breakfast. Then he stopped bringing it to dinner. Then Saturdays became a boundary rather than a luxury.",
        "His children began initiating conversations instead of waiting for him. His wife started asking for small things again—his opinion, or his hand on a walk. The change was not dramatic. It was the slow return of a man who had remembered that his presence was enough.",
      ] },
    ],
    quote: "Maryangel, I have been on many trips with my family. This was the first time I actually travelled with them.",
    quoteBy: "Richard · Egypt and Morocco · Solo + family",
  },
  {
    number: "03",
    slug: "team-journey-egypt-morocco",
    headline: "They worked in the same building for six years. They met in Egypt.",
    seoTitle: "A Private Team Journey Through Egypt and Morocco",
    description: "How a seven-night private journey through Egypt and Morocco helped four senior colleagues move beyond hierarchy and return with a more trusting way of working.",
    arc: "Exhausted, The Restoration · Team Journey",
    traveller: "Maryam, Faiza, Kaumi and Abdul-Azeez",
    destination: "Egypt and Morocco",
    dates: "13–20 August · Team of four",
    returnLabel: "Trust beyond deliverables",
    theme: "terracotta",
    relatedJourney: "/private-bespoke",
    relatedLabel: "Explore private journeys",
    intro: "They shared meetings, documents and six years of work. They needed to leave the building before they could become people to one another.",
    designedAround: "Displaced context. Shared silence. Meals where rank was irrelevant. Space for Maryam to lead differently and every member of the team to be heard.",
    sections: [
      { label: "01 · Before", title: "They were useful to one another, but unknown.", paragraphs: [
        "Maryam, Faiza, Kaumi and Abdul-Azeez worked in the same division of one of Nigeria's largest oil and gas corporations. They saw one another daily, sat in the same meetings and signed the same documents. They had worked together for six years.",
        "Hierarchy lived in every interaction: who spoke first, who sat where, who could push back and who could not. Trust was transactional, built on deliverables rather than seeing one another clearly.",
        "The team was functional but fragmented. Conversations stayed in safe territory. Vulnerability was a liability. A conventional team-building exercise would not be enough; they needed to be displaced from the roles that defined them.",
      ] },
      { label: "02 · The brief", title: "The hierarchy would not travel.", paragraphs: [
        "They booked seven nights in Egypt and Morocco—not a corporate retreat, but a private journey with shared spaces, meals that were not working dinners and mornings without agendas.",
        "Ryravel would not facilitate trust falls or strategy sessions. The design would create the conditions for colleagues to become people to one another. Their question was whether anything would remain once they returned to Lagos. Maryam, the most senior among them, believed the team could become more than a unit.",
      ] },
      { label: "03 · The turning point", title: "Four people admitted they did not have the answer.", paragraphs: [
        "On the second night in Egypt, a rooftop conversation began by accident. Abdul-Azeez, usually the quietest in meetings, mentioned a real fear about an upcoming project. Instead of offering a solution, Maryam shared her own. Then Faiza. Then Kaumi.",
        "There was no power play and no performance of competence. The next morning, Maryam initiated a conversation with Abdul-Azeez she would never have begun in Lagos—not because hierarchy had vanished, but because they had seen one another uncertain.",
      ] },
      { label: "04 · The Return", title: "The work stayed. The way they worked changed.", paragraphs: [
        "They did not return as instant friends. They returned as colleagues who understood one another. Maryam began opening conversations earlier. Faiza stopped over-explaining her ideas. Kaumi asked for input before giving directives. Abdul-Azeez raised concerns before they became crises.",
        "Trust had moved beyond deliverables. Its reference point was now the night in Egypt when four people could face the same uncertainty without rushing to fix it.",
      ] },
    ],
    quote: "Maryangel, we have done corporate trips before. This was the first time we came back as a team.",
    quoteBy: "Maryam, Faiza, Kaumi and Abdul-Azeez · Egypt and Morocco",
  },
  {
    number: "04",
    slug: "solo-restoration-zanzibar",
    headline: "She could name every risk except her own.",
    seoTitle: "A Solo Luxury Restoration Journey in Zanzibar",
    description: "A four-night solo stay at LUX Marijani, Zanzibar, designed to help a high-performing executive stop evaluating every moment and return lighter.",
    arc: "Exhausted, The Restoration · Solo Journey",
    traveller: "Faiza Dauda · Solo",
    destination: "Zanzibar, Tanzania",
    dates: "23–26 May · LUX Marijani",
    returnLabel: "Excellence without constant availability",
    image: "/journeys/ex9/exhausted-stone-town-spice.webp",
    imageAlt: "Warm spices in Stone Town, Zanzibar",
    theme: "spice",
    relatedJourney: "/journeys/exhausted",
    relatedLabel: "Explore restoration journeys",
    intro: "Faiza could evaluate every liability in a strategy. The journey was designed so that, for four nights, she would not have to evaluate herself.",
    designedAround: "Solo presence. Unstructured mornings. The Indian Ocean as the only agenda. Space to stop performing competence.",
    sections: [
      { label: "01 · Before", title: "Precision had become an identity.", paragraphs: [
        "Faiza Dauda built her career by being the most prepared person in the room. She could forecast a liability and find the gap in a strategy before the presenter reached the second slide.",
        "But precision is exhausting when it is turned inward. She measured rest by how productive she would be afterward, relationships by their utility and happiness by whether it was justified. The career was intact and the reputation solid, but she could not remember the last time she had done something without calculating the return.",
        "She was not burned out. She was accounted for—living in a ledger where every entry was correct and nothing felt like hers.",
      ] },
      { label: "02 · The brief", title: "Do not optimize this.", paragraphs: [
        "Faiza booked four solo nights at LUX Marijani in Zanzibar with no client, deck or outcome to justify the cost. Her hesitation was not travelling alone; she had done that often for work. It was being alone without an objective.",
        "A colleague had asked, “When did you last do something that made no sense on paper?” She went to find out.",
      ] },
      { label: "03 · The turning point", title: "The island did not need her to improve it.", paragraphs: [
        "Before sunrise on the second morning, Faiza walked to the beach. The wind moved through the palms in a rhythm she could not control. The waves arrived, broke and returned. No one was waiting for her analysis.",
        "Later in Stone Town, she watched a craftsman build a door by hand. No rush or efficiency metric—only a tradition older than her urgency. She stayed longer than intended. She did not take a photograph or research the history. She simply watched.",
      ] },
      { label: "04 · The Return", title: "The change appeared in small refusals.", paragraphs: [
        "Faiza did not return with a new life plan. She stopped bringing her laptop to bed, began taking lunch away from her desk and declined a project she could have handled because she no longer believed her value was proven by how much she carried.",
        "She could remain excellent at her work without being available for every demand.",
      ] },
    ],
    quote: "Maryangel, I have spent my career measuring everything. For three days in Zanzibar, I let the waves do the counting. I came back lighter than I have been in years.",
    quoteBy: "Faiza Dauda · Zanzibar · LUX Marijani",
  },
  {
    number: "05",
    slug: "restless-founder-doha-qatar",
    headline: "He went to Qatar looking for scale. He found a reason to slow down.",
    seoTitle: "A Bespoke Solo Journey in Doha, Qatar",
    description: "A four-night private Doha journey helped a restless founder stop turning every city into research and rediscover curiosity without an objective.",
    arc: "Restless, The Unleashing · Solo Journey",
    traveller: "Richard Okocha · Founder",
    destination: "Doha, Qatar",
    dates: "12–16 June · Solo",
    returnLabel: "Curiosity without extraction",
    theme: "dusk",
    relatedJourney: "/luxury-travel-planning",
    relatedLabel: "Explore restless journeys",
    intro: "Every trip had become reconnaissance disguised as travel. Doha gave Richard enough scale to see that speed was not the only thing worth studying.",
    designedAround: "Unscripted walking. The city as witness, not textbook. Space for curiosity without a pitch, playbook or landing page.",
    sections: [
      { label: "01 · Before", title: "He did not rest. He harvested.", paragraphs: [
        "Richard Okocha ran a Lagos company growing faster than he was. He called it opportunity, momentum and the hustle tax.",
        "He was curious about Qatar as raw material: how had Doha built so quickly, and what logic could he import? Every journey in five years had become due diligence. Even downtime had to produce something useful.",
        "By June, curiosity had become appetite. He consumed cities, conversations and his own energy at the same speed. He had trained himself to move so constantly that stillness felt like failure.",
      ] },
      { label: "02 · The brief", title: "Four nights with nothing to monetize.", paragraphs: [
        "Richard booked Doha telling himself he would study growth. The harder truth was that he no longer knew how to stand before something impressive without calculating its utility.",
        "Four days without meetings, pitch decks or founder dinners felt irresponsible. But something in him was tired of being useful, and he went anyway.",
      ] },
      { label: "03 · The turning point", title: "The skyline looked young from the desert.", paragraphs: [
        "Outside Doha, Richard watched the wind reshape dunes that predated the city. The skyline behind him looked small—not unimpressive, simply young. He realized the lesson was not Qatar's speed but the patience beneath it: the willingness to build beyond a quarterly timeline.",
        "In Souq Waqif, he watched an old man repair a dhow model. Richard did not ask for a card or consider a marketplace opportunity. Later he sat in the Museum of Islamic Art for two hours without turning the geometry into information. It was the longest he had been still in years.",
      ] },
      { label: "04 · The Return", title: "The company grew differently.", paragraphs: [
        "Richard returned without a Qatar expansion plan. He cancelled three meetings and gave his team one agenda-free afternoon each month—the freedom to be curious about something that would not appear on a spreadsheet.",
        "He stopped treating his own curiosity like a resource to be mined. The company did not immediately grow faster. It grew differently.",
      ] },
    ],
    quote: "Maryangel, I went to Qatar to study how fast a city could grow. I came back wondering how long I could stay still before I needed to make it useful.",
    quoteBy: "Richard Okocha · Doha, Qatar · Solo",
  },
  {
    number: "06",
    slug: "first-restorative-trip-kenya-egypt",
    headline: "One break a year. For ten years. Nothing ever shifted.",
    seoTitle: "A Restorative Private Journey Through Kenya and Egypt",
    description: "How an eight-night private journey through Kenya and Egypt helped an energy professional turn annual leave into a boundary that stayed with him.",
    arc: "Exhausted, The Restoration · Solo Journey",
    traveller: "Emmanuel · Energy professional",
    destination: "Kenya and Egypt",
    dates: "10–18 October · Solo",
    returnLabel: "A break that stayed",
    theme: "wild",
    relatedJourney: "/journeys/exhausted",
    relatedLabel: "Explore restoration journeys",
    intro: "For a decade, Emmanuel had taken one annual break and returned unchanged. Kenya and Egypt interrupted a pattern that better weather never could.",
    designedAround: "Wilderness before ancient water. No working holiday. Enough protected time for the body to stop treating leave as another performance cycle.",
    sections: [
      { label: "01 · Before", title: "His breaks changed the light, not the life.", paragraphs: [
        "Emmanuel worked in energy—the kind of work that does not pause when you do. For ten years, he honoured a contract with himself: one trip, once a year, then return and resume.",
        "Dubai, London and Accra all ended the same way: the same inbox, emails answered from a beach chair and rest treated as a transaction in exchange for sustained performance.",
        "By October, he was not burned out. He was habituated. His annual leave never changed the life waiting beneath it.",
      ] },
      { label: "02 · The brief", title: "An interruption, not another holiday.", paragraphs: [
        "He found Ryravel through a colleague. What stopped him was the premise of Exhausted, The Restoration: eight private nights across Kenya and Egypt, designed around recovery rather than selling a destination.",
        "He was skeptical. He had taken this trip before in different countries and with different companies. None had changed the pattern. He went anyway.",
      ] },
      { label: "03 · The turning point", title: "He remembered his own speed.", paragraphs: [
        "On the third morning in Kenya, a lioness crossed the track without hurry. She moved at the speed her body required, not the speed of targets or approval processes. Emmanuel realized he had not moved at his own speed in years.",
        "Later, beside the Nile at dusk, he watched the river until his phone died in his pocket. He did not charge it. That night he slept until morning without melatonin and, for the first time in a decade of annual leave, did not dream about his inbox.",
      ] },
      { label: "04 · The Return", title: "The interruption refused to leave.", paragraphs: [
        "Emmanuel returned to Lagos and did not check email for three days. Then he stopped answering messages after 7 pm and began declining meetings that could have been emails.",
        "The change was small and stubborn. It did not announce itself. It simply stayed.",
      ] },
    ],
    quote: "Maryangel, I have taken one break a year for ten years. This is the first time I came back and the break stayed with me.",
    quoteBy: "Emmanuel · Kenya and Egypt · Solo",
  },
  {
    number: "07",
    slug: "returning-guest-seychelles",
    headline: "He used to take one break a year. Then he came back to Ryravel.",
    seoTitle: "A Returning Guest's Private Seychelles Journey",
    description: "Why a returning Ryravel guest booked five unstructured nights in Seychelles—and changed rest from annual recovery into a continuing practice.",
    arc: "Exhausted, The Restoration · Returning Guest",
    traveller: "Emmanuel · Returning guest",
    destination: "Seychelles",
    dates: "6–11 July · Solo",
    returnLabel: "Rest as a practice",
    theme: "island",
    relatedJourney: "/private-bespoke",
    relatedLabel: "Explore private journeys",
    intro: "The first journey taught Emmanuel that he could stop. The second was designed to help him keep stopping before exhaustion made the decision for him.",
    designedAround: "Maintenance, not rescue. Five unstructured island nights. No breakthrough required—only space to remember what the first journey had made possible.",
    sections: [
      { label: "01 · Before", title: "He had never been a returning traveller.", paragraphs: [
        "One trip a year had been Emmanuel's rule for a decade—always a different company, always a different city and always the same return.",
        "Then a Ryravel journey through Kenya and Egypt changed the pattern. The break stayed with him. The 7 pm boundary held. His inbox remained outside his evenings.",
      ] },
      { label: "02 · The brief", title: "This time, the journey was maintenance.", paragraphs: [
        "A year later, Emmanuel did not search for a new operator. He returned to Ryravel and booked five solo nights in Seychelles with no itinerary and no objective except maintenance.",
        "He was no longer waiting until he was depleted enough to justify rest. The journey was designed to reinforce a practice before it became another rescue mission.",
      ] },
      { label: "03 · The turning point", title: "He did not need another breakthrough.", paragraphs: [
        "On the second day, Emmanuel floated in water clear enough to see his feet on the sand below. He was not escaping, recovering or earning anything. He was simply there.",
        "The first journey had taught him how to stop. The second was teaching him how to keep stopping. He did not need revelation; he needed to remember.",
      ] },
      { label: "04 · The Return", title: "One annual break became two.", paragraphs: [
        "Emmanuel changed his rule—not because he was more exhausted, but because rest was no longer annual maintenance. It had become a practice.",
        "He returned to Ryravel the following year, and the year after that. The strongest evidence was not a dramatic testimonial. It was the decision to come back.",
      ] },
    ],
    quote: "Maryangel, the first trip proved I could stop. The second trip proved I should keep stopping.",
    quoteBy: "Emmanuel · Returning Ryravel guest · Seychelles",
  },
];

export function caseStudyFor(slug) {
  return caseStudies.find((study) => study.slug === slug);
}
