import Link from "next/link";
import PolicyPage from "../components/PolicyPage";
import { buildMetadata } from "../seo";

export const metadata = buildMetadata({ title: "Privacy Notice", description: "How Ryravel handles journey enquiries, booking information, communications and website privacy choices.", path: "/privacy" });

export default function PrivacyPage() {
  return <PolicyPage title="Your details, treated with care." intro="We use the information you share to answer your request and arrange the journey you choose. This notice explains the main uses, recipients and choices." updated="25 September 2026">
    <section><h2>Who is responsible</h2><p>Ryravel is operated by Tourvana Inc, 2261 Market St, San Francisco, CA 94114, United States. For privacy questions or requests, email <a href="mailto:hello@ryravel.com">hello@ryravel.com</a>.</p></section>
    <section><h2>Information we collect</h2><p>When you enquire, we receive the name, email, telephone number, preferred contact method, how you feel, intended travel dates, journey length, party size, investment range, referral source and any message you provide. If you choose an existing journey, the request may also contain its name and page URL. We process booking and payment details when you proceed. We may need traveller identity, dietary, accessibility or other relevant details to arrange confirmed services; please share sensitive details only when needed.</p><p>Our site also processes technical information needed to operate and secure the request, including a source URL, browser information and a privacy-protective IP-derived value. The security check at final submission uses Cloudflare Turnstile. Theme and cookie choices are stored on your device. With your permission, our first-party analytics records a random session identifier, journey or case-study slug, selected feeling, form stage and validation-field names—not the answers or your contact details. The session identifier is not attached to your enquiry record.</p></section>
    <section><h2>Why we use it</h2><p>We use enquiry details to respond, design a proposal and take requested pre-booking steps. We use booking information to perform a confirmed journey contract, coordinate relevant suppliers, take payment, provide support and meet legal obligations. We use technical information to protect the site and investigate misuse. Depending on your location, the applicable legal basis may be pre-contractual steps, contract, legal obligation or our legitimate interest in running a secure service.</p><p>Occasional journey notes or case studies are sent only if you separately opt in, and you can unsubscribe at any time. Non-essential first-party analytics and marketing tracking are governed by your <Link href="/cookies">cookie choice</Link>.</p></section>
    <section><h2>Who may receive it</h2><p>Our enquiry system and customer relationship tools process identified requests so the curator team can reply. Email delivery and anti-abuse providers support the service. When you decide to book, we share only the details relevant to the properties, guides, transport providers and other local partners involved in your journey. Some recipients are in the destination country or elsewhere outside your home jurisdiction. We do not publish your enquiry or sell your contact details as a lead list. If you permit marketing tracking, LinkedIn may receive website interaction data under its own terms; reject it through Cookie settings if you do not want that tag loaded.</p></section>
    <section><h2>How long we keep it</h2><p>We keep information for as long as needed to answer your request, manage any booking, deal with disputes and comply with accounting or other legal duties. The period depends on whether you book and the applicable requirement. You can ask us about the period for your records; we review and delete information when it is no longer needed.</p></section>
    <section><h2>Your choices and rights</h2><p>You may ask to access or correct your information, object to or restrict certain uses, withdraw consent for optional analytics or marketing, or request deletion where applicable law allows. Some records must be retained for contractual or legal reasons. Contact <a href="mailto:hello@ryravel.com">hello@ryravel.com</a>; we may need to verify your identity. Depending on where you live, you may also complain to your local privacy regulator or have additional statutory rights.</p></section>
    <section><h2>Other sites and changes</h2><p>A supplier or external site has its own privacy practices when you visit it. We may update this notice as our services or legal duties change; the effective date above shows the current version.</p></section>
  </PolicyPage>;
}
