export const commercialServices = {
  "luxury-travel-planning": {
    slug: "luxury-travel-planning",
    title: "Worldwide Luxury Travel Planning",
    metaTitle: "Worldwide Luxury Travel Planner",
    description: "Private, bespoke luxury travel planning worldwide for couples, families, solo travellers and private groups—designed around your pace, priorities and reason for travelling.",
    kicker: "Private travel planning · worldwide",
    headline: "A luxury travel planner for the journey only you should take.",
    intro: "Ryravel designs private journeys worldwide for people who want the planning handled with judgement, discretion and care. We begin with what this trip needs to change, then select the destination, stays, guides, transfers and pace that serve it.",
    audience: "International luxury travellers, couples, families, solo travellers and private groups",
    keywords: ["luxury travel planner", "bespoke luxury travel", "private travel planner", "worldwide luxury travel", "custom luxury trips", "tailor-made luxury holidays"],
    pillars: [
      ["One considered brief", "Your dates, pace, interests, practical needs and emotional intent are held in one conversation rather than scattered across suppliers."],
      ["A journey built once", "We do not fit you into a catalogue. The destination and sequence are selected after we understand what the trip must do for you."],
      ["Human support", "A Ryravel curator reviews every request, shapes the proposal and remains your point of contact before and during travel."],
    ],
    arrangements: ["Private and boutique stays", "International and regional route design", "Private transfers and specialist guides", "Dining, access and meaningful experiences", "Rest, recovery and unstructured time", "24/7 support during the journey"],
    proof: { href: "/case-studies", label: "Read traveller case studies", title: "See what changed after the journey." },
    faq: [
      ["Where does Ryravel design journeys?", "Worldwide. Current published journeys show places where our design is already fully developed, while private requests can begin with a destination—or with no destination at all."],
      ["Is every Ryravel journey private?", "Our bespoke journeys are designed around your party. Private transfers, guides, stays and access are selected where they best serve the brief and remain subject to availability."],
      ["What investment should I expect?", "The planning conversation begins from $5,000 per person. The final investment depends on destination, season, journey length, party size, accommodation and access; nothing is booked until you approve the proposal."],
      ["How quickly will someone respond?", "A Ryravel curator reviews completed requests personally and responds within one business day."],
    ],
  },
  "luxury-family-travel": {
    slug: "luxury-family-travel",
    title: "Luxury Family Travel",
    metaTitle: "Luxury Family Travel Planner Worldwide",
    description: "Bespoke luxury family travel and multigenerational journeys worldwide, with private logistics, thoughtful pacing and experiences designed for every generation.",
    kicker: "Families & multigenerational travel",
    headline: "Luxury family travel that asks less of the family organiser.",
    intro: "A family journey should not move like an adult itinerary with children added later. Ryravel designs the rhythm, rooms, transfers, meals and experiences around the actual people travelling—so one person is not left managing everyone else’s holiday.",
    audience: "Families and multigenerational private groups seeking bespoke luxury travel",
    keywords: ["luxury family travel planner", "bespoke family holidays", "multigenerational luxury travel", "private family tours", "custom family vacations", "luxury family travel company"],
    pillars: [
      ["Every age considered", "Energy, attention, mobility, sleep and food are designed into the itinerary before a destination is finalised."],
      ["Fewer family decisions", "Private logistics and clear daily direction remove the invisible planning work that usually follows one parent on holiday."],
      ["Space to be together", "The itinerary protects unstructured time instead of filling every hour with activities children and adults must perform enjoying."],
    ],
    arrangements: ["Connected rooms, suites and private villas", "Private transfers with age-appropriate logistics", "Guides suited to the family dynamic", "Flexible meals and dietary planning", "Milestones and multigenerational celebrations", "24/7 support while travelling"],
    proof: { href: "/case-studies/family-journey-egypt-morocco", label: "Read the family case study", title: "He had taken his family on vacation before. He had never taken them on a trip." },
    faq: [
      ["Can Ryravel plan for several generations?", "Yes. We plan around the different pace, mobility, rooming, dietary and attention needs within one family, then choose properties and experiences that allow everyone to travel well together."],
      ["Can children’s activities and adult time coexist?", "Yes. The purpose is not to keep every person occupied at every moment. We create a rhythm with shared experiences, protected adult time and enough flexibility for the day to change."],
      ["Do you arrange private transfers and guides?", "Yes, where they serve the journey. Exact arrangements depend on destination, party size, dates and availability and are confirmed in your proposal."],
      ["How far ahead should a family enquire?", "For school holidays, milestone trips and larger multigenerational parties, earlier is better. Share your dates even if they are approximate and the curator team will advise what is realistic."],
    ],
  },
  "luxury-honeymoons": {
    slug: "luxury-honeymoons",
    title: "Luxury Honeymoons",
    metaTitle: "Bespoke Luxury Honeymoon Planner Worldwide",
    description: "Bespoke luxury honeymoon planning worldwide, with private stays, seamless logistics and a journey designed around how two people want to begin married life.",
    kicker: "Honeymoons & journeys for two",
    headline: "A honeymoon designed for the two people taking it.",
    intro: "The best honeymoon is not the most crowded itinerary or the most photographed resort. It is a private journey whose pace, setting and moments feel unmistakably yours—especially after months of making decisions for everyone else.",
    audience: "Couples seeking a private, bespoke luxury honeymoon worldwide",
    keywords: ["luxury honeymoon planner", "bespoke honeymoon", "private honeymoon travel", "luxury honeymoon packages worldwide", "tailor-made honeymoon", "luxury travel for couples"],
    pillars: [
      ["The right contrast", "City and coast, wilderness and island, movement and stillness are sequenced to create a journey rather than a list of hotels."],
      ["Privacy with texture", "Private does not have to mean isolated. We balance time alone with people, food, place and experiences worth remembering together."],
      ["No planning hangover", "Transfers, timing, room categories and special moments are settled before departure so the honeymoon does not become another project."],
    ],
    arrangements: ["Private villas, suites and hideaways", "Multi-stop and multi-country routing", "Private transfers and guides", "Dining and celebration moments", "Restorative time after the wedding", "24/7 support during travel"],
    proof: { href: "/case-studies", label: "Read traveller case studies", title: "See how considered travel changes the way people return." },
    faq: [
      ["Does Ryravel offer honeymoon packages?", "We design bespoke honeymoons rather than fixed packages. Published journeys can be a starting point, but the final route, stays and pace are built around the couple."],
      ["Can you combine more than one destination?", "Yes. We often use contrast deliberately, such as culture followed by coast or wilderness followed by an island. The route must earn its complexity rather than adding movement for its own sake."],
      ["Can we begin without choosing a destination?", "Yes. Tell us the dates, investment range and how you want the honeymoon to feel. We can recommend the destination after understanding the brief."],
      ["When should we begin planning?", "Begin as soon as your likely dates and investment direction are known. Earlier enquiries create more choice for highly private stays, premium room categories and complex routes."],
    ],
  },
  "luxury-wellness-retreats": {
    slug: "luxury-wellness-retreats",
    title: "Luxury Wellness Retreats",
    metaTitle: "Private Luxury Wellness Retreat Planner",
    description: "Private luxury wellness retreat planning worldwide, designed around rest, recovery and sustainable return—not a generic spa itinerary or medical promise.",
    kicker: "Restorative travel · worldwide",
    headline: "A private wellness journey designed around what recovery means to you.",
    intro: "Some travellers need sleep and protected silence. Others need movement, nature, nourishing food or expert-led practice. Ryravel designs restorative journeys around the person—not a generic wellness menu—and never substitutes travel for medical care.",
    audience: "Travellers seeking private luxury wellness retreats, restorative travel and unhurried recovery",
    keywords: ["luxury wellness retreat planner", "private wellness retreat", "bespoke wellness travel", "luxury restorative retreat", "burnout recovery retreat travel", "wellness holidays worldwide"],
    pillars: [
      ["Rest before programming", "We protect sleep, silence and unscheduled time before deciding which treatments or practices deserve a place."],
      ["The right environment", "Coast, forest, mountain, desert and wilderness affect people differently. The setting is selected for the condition you arrive in."],
      ["A return you can keep", "The journey closes deliberately, with enough space to understand what should—and should not—follow you home."],
    ],
    arrangements: ["Private restorative stays", "Spa and non-clinical wellness experiences", "Nature, movement and contemplative time", "Nourishing dining and dietary coordination", "Unstructured days and digital boundaries", "24/7 support during the journey"],
    proof: { href: "/case-studies/solo-restoration-zanzibar", label: "Read a restoration case study", title: "She could name every risk except her own." },
    faq: [
      ["Is this a medical wellness programme?", "No. Ryravel designs travel and non-clinical restorative experiences. We do not diagnose conditions or replace medical care. Any clinical programme would need to be delivered and governed by the qualified provider concerned."],
      ["Can I travel alone?", "Yes. Solo journeys can be designed around privacy, appropriate support and a pace that does not require you to perform being sociable."],
      ["Do I have to follow a fixed schedule?", "No. We protect unstructured time and only add experiences that serve the brief. The exact degree of structure is agreed with you before booking."],
      ["Can a wellness journey be designed anywhere?", "Worldwide, subject to whether the destination and available partners can genuinely support the brief. We recommend place only after understanding what you need from the journey."],
    ],
  },
  "luxury-corporate-retreats": {
    slug: "luxury-corporate-retreats",
    title: "Luxury Corporate Retreats",
    metaTitle: "Luxury Corporate Retreat & Incentive Travel",
    description: "Private luxury corporate retreats and incentive journeys worldwide for leadership teams and small groups, with purposeful design and seamless logistics.",
    kicker: "Leadership teams & private groups",
    headline: "A corporate retreat where the hierarchy does not travel.",
    intro: "Ryravel designs private journeys for leadership teams and small groups who need more than a meeting in a better hotel. Shared context, considered pacing and moments without an agenda can change how people see—and work with—one another.",
    audience: "Leadership teams, executive groups and companies seeking private luxury retreats or incentive travel",
    keywords: ["luxury corporate retreat", "executive retreat planner", "luxury incentive travel", "leadership retreat travel", "bespoke corporate travel", "private team retreat"],
    pillars: [
      ["Purpose before programme", "We clarify whether the journey must reward, reconnect, reset or open a strategic conversation before building the agenda."],
      ["Shared experience, no theatre", "The design creates conditions for honest interaction without relying on forced exercises or generic team-building rituals."],
      ["One operational thread", "Rooming, transfers, privacy, dietary needs, leadership requirements and changes are coordinated through one curator team."],
    ],
    arrangements: ["Private-use stays and meeting spaces", "Executive and small-group logistics", "Shared cultural and wilderness experiences", "Private dining and milestone moments", "Optional facilitated working time", "24/7 support while travelling"],
    proof: { href: "/case-studies/team-journey-egypt-morocco", label: "Read the team journey case study", title: "They worked in the same building for six years. They met in Egypt." },
    faq: [
      ["What size corporate group does Ryravel design for?", "Our strength is considered travel for leadership teams and small private groups. Share your group size and purpose and we will confirm whether the brief is the right fit."],
      ["Can a retreat include working sessions?", "Yes. We can protect focused working time without letting the journey become an off-site office. Space, privacy and technical needs are confirmed during planning."],
      ["Do you arrange incentive travel?", "Yes, when the brief calls for a private, high-touch journey rather than a mass group programme. Recognition, celebration and shared memory can be designed into the route."],
      ["Can the destination remain confidential during early planning?", "Yes. The first conversation can begin with the purpose, dates, group and investment direction. Destination options are introduced only after the brief is understood."],
    ],
  },
};

export const commercialServiceOrder = [
  "luxury-travel-planning",
  "luxury-family-travel",
  "luxury-honeymoons",
  "luxury-wellness-retreats",
  "luxury-corporate-retreats",
];
