export const arcs = [
  {
    id: "exhausted",
    label: "Exhausted - The Restoration",
    title: "Exhausted - The Restoration",
    shortTitle: "Exhausted - The Restoration",
    subtitle: "From depletion to restoration",
    intro: "Four restorative journeys for the person who has been running on empty and needs more than a holiday. They need permission to stop, recover and return to themselves.",
    story: "The exhausted traveller is not merely tired. They are depleted. Tired can be helped by a week off. Depletion asks for a deliberate pace, an environment with no demands, and a sequence that moves from rest into genuine restoration.",
    color: "#d7a252",
    principles: [
      ["Permission", "Coast, stillness, no agenda. The body must understand that it is allowed to stop."],
      ["Dissolution", "Spa, beach, and the complete absence of schedule remove every ordinary demand."],
      ["Awakening", "On longer arcs, the Serengeti follows. Curiosity returns before effort does."],
      ["The Return", "A final integration, the Departure Box, and the flight home carrying a different weight."],
    ],
  },
  {
    id: "romantic",
    label: "Romantic - The Reawakening",
    title: "Romantic - The Reawakening",
    shortTitle: "Romantic - The Reawakening",
    subtitle: "Zanzibar does not make people fall in love. It gives people already in love somewhere worthy of that fact.",
    intro: "Three journeys for couples, each built around a private villa, one extraordinary shared experience per day, and three Ryravel Signatures designed for two people.",
    story: "The romantic journey is not designed for romance as performance. It is designed for proximity: two people in the same place, without ordinary demands, long enough for something to shift.",
    color: "#cf708b",
    principles: [
      ["A private villa", "Your own pool, terrace and beach access. Service appears only when summoned."],
      ["One meaningful experience", "One thing each day that earns its place. The remaining time belongs to two people."],
      ["The Couple’s Gift", "A kaftan, a kikoi and two different handwritten cards."],
      ["Two Departure Boxes", "One for each person, written to them as themselves rather than as a unit."],
    ],
  },
  {
    id: "adventurous",
    label: "Restless - The Unleashing",
    title: "Restless - The Unleashing",
    shortTitle: "Restless - The Unleashing",
    subtitle: "I will know what I am made of.",
    intro: "Three journeys to Uhuru Peak. The summit, then the Serengeti, then the crater—in the sequence the body needs to receive each one.",
    story: "The adventurous traveller does not need a challenge for its own sake. They need to discover something about themselves ordinary life cannot reveal.",
    color: "#2aa6ca",
    principles: [
      ["WFR-certified lead guide", "Altitude is assessed nightly by guides who have summited hundreds of times."],
      ["The Summit Gift", "A river stone, Maasai beadwork and a handwritten note arrive before midnight."],
      ["The Serengeti portrait", "The face the mountain made, documented at golden hour on the plains."],
      ["The Departure Box", "Your certificate, volcanic stone, guide’s note and a letter from Ryravel."],
    ],
  },
  {
    id: "social",
    label: "Isolated - The Gathering",
    title: "Isolated - The Gathering",
    shortTitle: "Isolated - The Gathering",
    subtitle: "Connected to My People",
    intro: "Three journeys for groups of four to eight friends. One vehicle. One table. Experiences that create shared memory rather than parallel private ones.",
    story: "Every Social journey follows the same arc: observation first, participation next, celebration to close. The group photograph in every Departure Box is the proof: you were here together.",
    color: "#e27335",
    principles: [
      ["Observe", "Enter without expectations. Context comes before participation."],
      ["Participate", "Cook, sail, make and learn together. Shared physical memories become social substance."],
      ["Celebrate", "Music or ceremony arrives once the group has enough shared experience to receive it."],
      ["Carry it home", "Every individual box contains the same group photograph."],
    ],
  },
  {
    id: "stillness",
    label: "Stillness · Deep Presence & Wilderness Solitude",
    title: "The Stillness Collection",
    shortTitle: "Stillness",
    subtitle: "You came here to need less.",
    intro: "Ten wilderness journeys for travellers who are not asking for a safari. They are asking to stop being asked for anything.",
    story: "The Stillness Collection replaces the printed safari schedule with an emotional rhythm. The guest chooses each morning. Guides hold silence, wellness work is integrated, and every landscape is selected for what it allows the nervous system to release.",
    color: "#7a9a7a",
    principles: [
      ["Less, deliberately", "One or two landscapes, chosen as emotional architecture rather than a checklist of sightings."],
      ["Silence as method", "Game drives become moving meditation, with guides trained to speak only when invited."],
      ["The Silent Documentary", "Nothing posed or staged. A hand-bound album arrives weeks after the traveller returns."],
      ["The arc closes", "Founder calls, a Departure Box and a written integration bring the experience home."],
    ],
  },
  {
    id: "disconnected",
    label: "Disconnected - The Return",
    title: "Disconnected - The Return",
    shortTitle: "Disconnected - The Return",
    subtitle: "Reconnect to the earth, to life arriving and departing, to yourself.",
    intro: "Four seasonal wilderness journeys designed to interrupt disconnection: three across the calving plains and one inside the great migration.",
    story: "The disconnected traveller does not need another screen-free promise. They need the wild to interrupt them. These journeys move from a soft landing into genuine isolation, then close through the crater and a deliberate human return.",
    color: "#4a7e2a",
    principles: [
      ["Land & strip back", "Step off the aircraft and onto the plains. No lobby, no unnecessary transition."],
      ["Enter the ecosystem", "Mobile camps and fly camps place the traveller inside the movement rather than beside it."],
      ["Receive the unexpected", "A walk into the herd or migration is held back until the emotional moment is right."],
      ["Reconnect & carry", "The crater, a field note and the Departure Box close the return."],
    ],
  },
];

export const journeys = [
  {
    slug: "the-reset",
    arc: "exhausted",
    nights: 5,
    days: 6,
    title: "The Reset",
    destination: "Zanzibar · Tanzania",
    tagline: "Five nights. One island. No syllabus for rest.",
    description: "A five-night private Zanzibar wellness retreat with sunrise beach yoga, Ayurvedic consultations, unstructured afternoons and evening rituals, designed for the traveller who is tired of performing rest.",
    tags: ["Year-round", "Coastal wellness", "Private retreat"],
    price: "$12,618",
    priceNote: "From $12,618 per person based on two sharing · seasonal pricing confirmed for your dates",
    image: "/journeys/the-reset/zanzibar-beach.jpg",
    images: ["/journeys/the-reset/zanzibar-beach.jpg", "/journeys/the-reset/wellness-treatment.jpg"],
    imageAlt: "Aerial view of a quiet palm-lined Zanzibar beach and turquoise water",
    seoTitle: "The Reset: 5-Night Private Zanzibar Wellness Retreat",
    seoDescription: "Five nights of private coastal wellness in Zanzibar: sunrise yoga, Ayurvedic treatments, unstructured afternoons and a gentler return. From $12,618 per person sharing.",
    keywords: ["private Zanzibar wellness retreat", "luxury Zanzibar wellness holiday", "five night Zanzibar retreat", "Zanzibar Ayurveda retreat", "Zanzibar beach yoga retreat", "private luxury wellness travel", "restorative Zanzibar holiday", "Exhausted The Restoration"],
    availableMonths: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    tripOrigin: "Zanzibar, Tanzania",
    phases: ["You Are Here Now", "The Body Remembers", "The Island as Teacher", "Sand, Sky, Nothing Else", "The Morning You Didn't Expect", "Late Checkout. The Return Begins."],
    faqs: [
      { question: "When can I take The Reset?", answer: "The Reset is designed for departures throughout the year. Pricing varies by season and the resort and practitioner schedule must be confirmed for your chosen dates before anything is booked." },
      { question: "How are the five nights paced?", answer: "Each full day is framed by a morning practice and an evening ritual, while roughly 10 a.m. to 5 p.m. is intentionally left largely unscheduled. Day 1 is arrival and Day 6 is a slow departure with late checkout." },
      { question: "What does the starting investment include?", answer: "The proposed journey includes five nights in Zanzibar, transfers, morning practices, evening treatments, Ayurvedic consultations, listed activities, Signature Rituals and Ryravel host support. International flights are excluded; no internal flights are planned. Your personal proposal will confirm the named property, practitioner availability, exact inclusions and final price." },
      { question: "Is this a medical treatment programme?", answer: "No. The Reset is a private wellness journey, not a medical or therapeutic treatment plan. Share any health needs or contraindications with your curator and qualified practitioners before confirming treatments." },
      { question: "Can I travel solo?", answer: "Yes. The published starting price assumes two people sharing. Tell us if you are travelling alone and a curator will confirm the suitable room arrangement and exact solo investment." },
    ],
  },
  { slug: "ex6", arc: "exhausted", nights: 11, title: "Exhausted, The Restoration", destination: "Zanzibar · Serengeti · Ngorongoro", tagline: "I arrived heavy with everything my life had asked of me. Eleven nights later, I understood what it means to put something down.", description: "The complete restoration arc across coast, plains and crater.", tags: ["Beach", "Safari", "Crater"], price: "$43,500", image: "/journeys/ex6/exhausted-ngorongoro-sunset.webp", imageAlt: "Sunset over the Ngorongoro landscape from a private lodge deck", phases: ["Dissolve", "Awaken", "Descend", "Close & Carry"] },
  { slug: "ex9", arc: "exhausted", nights: 6, title: "Exhausted, The Restoration", destination: "Zanzibar", tagline: "Six nights. One island. Nothing asked of me except to stop.", description: "Pure decompression on Zanzibar: coast, spa, Stone Town and the permission to stop.", tags: ["Beach", "Spa", "Stone Town"], price: "$14,033", image: "/journeys/ex9/exhausted-zanzibar-coast.webp", imageAlt: "The quiet Zanzibar coastline beneath a clear blue sky", phases: ["Arrive & Exhale", "Stillness Deepens", "Close & Carry"] },
  { slug: "rn9", arc: "exhausted", nights: 9, title: "Exhausted, The Restoration", destination: "Zanzibar · Serengeti", tagline: "Beach, then wilderness.", description: "Nine nights of pure decompression across Zanzibar and the Serengeti, with a quiet coastal landing before the return.", tags: ["Zanzibar", "Serengeti", "Tented camp"], price: "$26,611", phases: ["Dissolve", "Awaken", "Return"], image: "/journeys/rn9/exhausted-serengeti-camp.webp", imageAlt: "A tented camp beneath a dramatic sky on the Serengeti plains" },
  {
    slug: "calving-season",
    arc: "stillness",
    nights: 6,
    days: 7,
    title: "The Calving Season",
    destination: "Southern Serengeti · Ndutu · Ngorongoro · Tanzania",
    tagline: "Six nights on the calving plains. Nothing to make lighter.",
    description: "A six-night private Tanzania safari through the Southern Serengeti, Ndutu calving plains and Ngorongoro Crater, designed for presence in the January–March calving season.",
    tags: ["Jan–Mar", "Ndutu calving season", "Private safari"],
    price: "$11,075",
    priceNote: "From $11,075 per person in March · January and February pricing confirmed for your dates",
    image: "/journeys/calving-season/southern-serengeti-aerial.webp",
    images: ["/journeys/calving-season/southern-serengeti-aerial.webp", "/journeys/calving-season/camp-hospitality.webp"],
    imageAlt: "Aerial view of a secluded safari camp on broad, sunlit plains",
    seoTitle: "The Calving Season: 6-Night Private Ndutu Safari",
    seoDescription: "A six-night private calving-season safari in Tanzania: Southern Serengeti, Ndutu and Ngorongoro. January–March departures from $11,075 per person.",
    keywords: ["private Ndutu safari", "Serengeti calving season safari", "luxury Tanzania calving safari", "Southern Serengeti safari January to March", "Ndutu wildebeest calving safari", "private Ngorongoro safari", "six night Tanzania safari", "Stillness Collection"],
    availableMonths: ["January", "February", "March"],
    accommodation: "Southern Serengeti camp · Ndutu mobile luxury camp · Ngorongoro crater-rim stay",
    phases: ["Land & Open", "The Plains in Full Life", "Ndutu, the Heart of the Calving", "The Hunt and the Birth", "The Morning You Don't Expect", "The Crater", "Last Morning. The Return."],
    faqs: [
      { question: "When can I take The Calving Season journey?", answer: "This six-night edition is offered January through March. February is the peak calving window described in the journey; wildlife encounters and exact camp availability can never be guaranteed. Your curator will confirm the best departure and current price for your dates." },
      { question: "Where does the six-night journey go?", answer: "The journey spends nights 1–2 on the Southern Serengeti plains, nights 3–5 at a mobile camp in Ndutu and night 6 near the Ngorongoro Crater. Day 7 is the return and departure." },
      { question: "What does the starting investment include?", answer: "The proposed journey includes internal flights, camp transfers, game drives, the senior tracker day, Signature Rituals and Ryravel host support. International flights are excluded. Your personal proposal will confirm the named camps, full inclusions, exclusions and final price before booking." },
      { question: "Can the journey be planned for one person?", answer: "Yes. Tell us whether you will travel solo or with others. The published starting price is per person; a curator will confirm the arrangement and exact investment for your party." },
    ],
  },
  {
    slug: "calving-isolation",
    arc: "stillness",
    nights: 7,
    days: 8,
    title: "Calving Maximum Isolation",
    destination: "Southern Serengeti · Ndutu · Ngorongoro · Tanzania",
    tagline: "Seven nights. Fly camp. Calving plains. Nowhere left to get ahead to.",
    description: "A seven-night private calving-season safari across the Southern Serengeti, a secluded Ndutu fly camp, a mobile luxury camp and Ngorongoro Crater. January–March departures.",
    tags: ["Jan–Mar", "Ndutu fly camp", "Private safari"],
    price: "$11,814",
    priceNote: "From $11,814 per person in March · January and February pricing confirmed for your dates",
    image: "/journeys/calving-isolation/safari-drive-at-sunset.webp",
    images: ["/journeys/calving-isolation/safari-drive-at-sunset.webp", "/journeys/calving-isolation/guided-nature-walk.webp"],
    imageAlt: "Safari vehicle beneath an acacia tree on open plains at sunset",
    seoTitle: "Calving Maximum Isolation: 7-Night Private Ndutu Safari",
    seoDescription: "Seven nights across the Southern Serengeti, a secluded Ndutu fly camp, mobile luxury camp and Ngorongoro Crater. Private January–March safari from $11,814 per person.",
    keywords: ["private Ndutu fly camp safari", "luxury Serengeti calving season safari", "seven night Tanzania safari", "Southern Serengeti private safari", "Ndutu calving season safari", "Ngorongoro crater private safari", "off-grid Tanzania safari", "Stillness Collection"],
    availableMonths: ["January", "February", "March"],
    accommodation: "Southern Serengeti camp · Ndutu fly camp · Ndutu mobile luxury camp · Ngorongoro crater-rim stay",
    phases: ["The World Falls Away", "The Full Ecosystem", "Into the Calving Ground", "On Foot in the Calving Plains", "The Morning After", "Chosen Day", "The Crater", "Last Morning. The Return."],
    faqs: [
      { question: "When can I take Calving Maximum Isolation?", answer: "This seven-night edition is designed for January through March. February is the peak calving period described in the journey, but wildlife movement and sightings are never guaranteed. Your curator will confirm the best available departure and exact price for your dates." },
      { question: "How are the seven nights divided?", answer: "Nights 1–2 are on the Southern Serengeti plains, nights 3–4 at the Ndutu fly camp, nights 5–6 at the Ndutu mobile luxury camp and night 7 near Ngorongoro Crater. Day 8 is the return and departure." },
      { question: "What does the starting investment include?", answer: "The proposed journey includes internal flights, fly-camp and mobile-camp accommodation, a full-day crater descent, the planned Maasai family visit, Signature Rituals and Ryravel host support. International flights are excluded. Your personal proposal will confirm named camps, arrangements, full inclusions, exclusions and final price before booking." },
      { question: "What should I expect at the fly camp?", answer: "The fly-camp phase is deliberately more stripped back than the mobile luxury camp that follows it. We will explain the actual tent, facilities, safety arrangements and accessibility for your departure before you decide whether this is right for you." },
      { question: "Can this journey be arranged for a solo traveller?", answer: "Yes. Share your party size with a curator and we will confirm the available arrangements and exact investment. The published starting price is per person for March departures." },
    ],
  },
  {
    slug: "full-calving-arc",
    arc: "stillness",
    nights: 9,
    days: 10,
    title: "The Full Calving Arc",
    destination: "Southern Serengeti · Ndutu · Ngorongoro · Tanzania",
    tagline: "Nine nights. Lodge to fly camp to crater. A return to being part of it.",
    description: "A nine-night private calving-season safari through the Southern Serengeti, Ndutu mobile camp, an off-grid fly camp and Ngorongoro Crater, designed for a deeper return to presence.",
    tags: ["Jan–Mar", "Four settings", "Private calving safari"],
    price: "$15,377",
    priceNote: "From $15,377 per person in March · January and February pricing confirmed for your dates",
    image: "/journeys/full-calving-arc/camp-fire-on-plains.webp",
    images: ["/journeys/full-calving-arc/camp-fire-on-plains.webp", "/journeys/full-calving-arc/guided-plains-walk.webp"],
    imageAlt: "Quiet fireside seating overlooking open safari plains at dusk",
    seoTitle: "The Full Calving Arc: 9-Night Private Serengeti Safari",
    seoDescription: "A nine-night private Serengeti calving safari: Southern Serengeti lodge, Ndutu mobile camp, off-grid fly camp and Ngorongoro Crater. January–March from $15,377 per person.",
    keywords: ["nine night Serengeti calving safari", "private Ndutu calving safari", "Southern Serengeti luxury safari", "Ndutu mobile camp safari", "private Tanzania fly camp", "Ngorongoro Crater private safari", "luxury calving season tour Tanzania", "Stillness Collection"],
    availableMonths: ["January", "February", "March"],
    accommodation: "Southern Serengeti lodge · Ndutu mobile luxury camp · Ndutu fly camp · Ngorongoro crater-rim stay",
    phases: ["The World Falls Away", "The Serengeti Opens", "Into the Calving, Hunt, Birth, Survival", "The Migration in Golden Light", "The Last Step Away", "Walking into the Birth", "The Crater. Ancient World.", "Into the Caldera", "The Maasai Morning. The Return."],
    faqs: [
      { question: "When can I take The Full Calving Arc?", answer: "This nine-night edition is designed for January through March. February is typically the peak calving window in this journey design, but wildlife movement and sightings can never be guaranteed. Your curator will confirm the available departure and exact price for your dates." },
      { question: "How are the nine nights divided?", answer: "Nights 1–2 are at a Southern Serengeti lodge, nights 3–5 at a Ndutu mobile luxury camp, nights 6–7 at an off-grid fly camp, and nights 8–9 near Ngorongoro Crater. Day 10 is the return and departure." },
      { question: "What does the starting investment include?", answer: "The proposed journey includes internal flights, all listed accommodation, a full-day crater descent, the planned Maasai family visit, Signature Rituals and Ryravel host support. International flights are excluded. Your personal proposal will confirm named properties, arrangements, all inclusions and exclusions, and the final price before booking." },
      { question: "What should I expect at the fly camp?", answer: "The fly-camp phase is intentionally simpler than the lodge and mobile luxury camp. We will explain the actual tent, facilities, safety arrangements and accessibility for your departure before you decide whether it is right for you." },
      { question: "Can this journey be arranged for a solo traveller?", answer: "Yes. Share your party size with a curator and we will confirm the available arrangements and exact investment. The published starting price is per person for March departures." },
    ],
  },
  {
    slug: "kimbilio",
    arc: "stillness",
    nights: 4,
    days: 5,
    title: "Kimbilio",
    destination: "Katavi National Park · Tanzania",
    tagline: "A place the world cannot reach you.",
    description: "A four-night, fly-in private luxury safari in remote Katavi National Park, designed around solitude, stillness and the relief of becoming unreachable.",
    tags: ["Jun–Oct", "Fly-in only", "Private stillness safari"],
    price: "$5,500",
    priceNote: "From $5,500 per person sharing",
    image: "/journeys/kimbilio/katavi-sunset.jpg",
    images: ["/journeys/kimbilio/katavi-sunset.jpg", "/journeys/kimbilio/katavi-floodplain.jpg"],
    imageAlt: "Sunset through acacia trees in remote Katavi National Park, Tanzania",
    seoTitle: "Kimbilio: Private Luxury Katavi Safari",
    seoDescription: "A four-night fly-in private luxury safari in Katavi National Park, Tanzania, designed for stillness, solitude and restoration. From $5,500 per person sharing.",
    keywords: ["private Katavi safari", "luxury Katavi safari", "Katavi National Park safari", "fly-in Tanzania safari", "remote Tanzania safari", "secluded African safari", "luxury safari for rest", "Stillness Collection"],
    availableMonths: ["June", "July", "August", "September", "October"],
    accommodation: "Mbali Mbali Katavi",
    tripOrigin: "Arusha, Tanzania",
    phases: ["The Leaving", "Unreachable", "The Middle of Nowhere", "Being Found by Yourself", "The Return Crossing"],
    faqs: [
      { question: "When can I take the Kimbilio journey?", answer: "This Kimbilio edition is designed for June through October, when Katavi is accessible for the remote fly-in journey described here. Your curator confirms camp and charter space for your exact dates before anything is booked." },
      { question: "How do I reach Katavi?", answer: "Kimbilio begins from Arusha and continues by shared charter to Ikuu Airstrip, with the onward camp transfer arranged for you. International flights to Arusha are not included." },
      { question: "What does the starting investment include?", answer: "The starting investment includes shared charter flights, four nights full board with drinks at meals, two daily game drives, the Usiku night drive, a walking safari, park and concession fees, emergency medical evacuation cover, the Departure Box, and two curator check-ins after your return." },
      { question: "Can I take Kimbilio alone?", answer: "Yes. The published starting investment is per person sharing; tell us if you are travelling alone and your curator will confirm the private solo investment for your dates." },
    ],
  },
  {
    slug: "kimya",
    arc: "stillness",
    nights: 4,
    days: 5,
    title: "Kimya",
    destination: "Rubondo Island · Lake Victoria · Tanzania",
    tagline: "The first silence you've heard in years.",
    description: "A four-night, fly-in private luxury safari on Rubondo Island, designed around true quiet, Lake Victoria and the relief of hearing yourself again.",
    tags: ["No road in", "Lake Victoria", "Private stillness safari"],
    price: "$9,950",
    priceNote: "From $9,950 per person sharing",
    image: "/journeys/kimya/rubondo-island.jpg",
    images: ["/journeys/kimya/rubondo-island.jpg", "/journeys/kimya/rubondo-birds.jpg"],
    imageAlt: "Rubondo Island rising from the quiet waters of Lake Victoria, Tanzania",
    seoTitle: "Kimya: Private Luxury Rubondo Island Safari",
    seoDescription: "A four-night private luxury safari on Rubondo Island, Lake Victoria, designed for silence, solitude and restoration. From $9,950 per person sharing.",
    keywords: ["private Rubondo Island safari", "luxury Rubondo Island safari", "Rubondo Island Camp", "Lake Victoria safari Tanzania", "fly-in Tanzania island safari", "chimpanzee safari Rubondo", "private quiet safari", "luxury Tanzania safari for rest"],
    availableMonths: ["January", "February", "March", "June", "July", "August", "September", "October", "November", "December"],
    accommodation: "Rubondo Island Camp",
    tripOrigin: "Mwanza, Tanzania",
    phases: ["The Crossing", "The First Silence", "The Middle of the Lake", "Hearing Yourself Again", "The Return"],
    faqs: [
      { question: "When can I take the Kimya journey?", answer: "Rubondo Island Camp operates from June through March and closes in April and May for the long rains. June through October is the cooler, drier window; your curator will match the dates to the kind of quiet and wildlife experience you want." },
      { question: "How do I reach Rubondo Island?", answer: "Kimya is a fly-in island journey beginning from Mwanza. Ryravel coordinates the internal flight and island transfers; international flights to and from Mwanza are not included." },
      { question: "What does the starting investment include?", answer: "The starting investment includes internal flights and transfers, four nights at Rubondo Island Camp on full board with house drinks, camp activities, The Listening, the Departure Box, and the Ryravel journal. Premium spirits, gratuities, personal purchases, and travel insurance beyond the stated medical evacuation cover are excluded." },
      { question: "Can Kimya be designed for a solo traveller?", answer: "Yes. The published starting investment is per person sharing. Share that you are travelling alone and your curator will confirm the solo arrangement and exact investment for your dates." },
    ],
  },
  {
    slug: "kupona",
    arc: "stillness",
    nights: 4,
    days: 5,
    title: "Kupona",
    destination: "Matetsi Private Reserve · Victoria Falls · Zimbabwe",
    tagline: "Where what is depleted is restored.",
    description: "A four-night private luxury retreat at Matetsi Victoria Falls, designed around unstructured rest, Zambezi stillness and the slow restoration of depleted energy.",
    tags: ["Jan–Mar", "Zambezi River", "Private restoration retreat"],
    price: "$5,750",
    priceNote: "From $5,750 per person sharing",
    image: "/journeys/kupona/matetsi-river-suite.jpg",
    images: ["/journeys/kupona/matetsi-river-suite.jpg", "/journeys/kupona/zambezi-boat-aerial.jpg"],
    imageAlt: "A private plunge pool overlooking the Zambezi River at Matetsi Victoria Falls, Zimbabwe",
    seoTitle: "Kupona: Private Luxury Victoria Falls Retreat",
    seoDescription: "A four-night private luxury retreat at Matetsi Victoria Falls, Zimbabwe, designed for deep rest and restoration beside the Zambezi River. From $5,750 per person sharing.",
    keywords: ["luxury Victoria Falls retreat", "private Victoria Falls safari", "Matetsi Victoria Falls luxury", "Zambezi River luxury retreat", "Zimbabwe wellness retreat", "luxury safari for burnout recovery", "restorative African safari", "Stillness Collection"],
    availableMonths: ["January", "February", "March"],
    accommodation: "Matetsi Victoria Falls",
    tripOrigin: "Victoria Falls, Zimbabwe",
    phases: ["The Landing", "Water, Not Walls", "The Long Middle", "Strength Returns", "The Return"],
    faqs: [
      { question: "When can I take the Kupona journey?", answer: "This Kupona edition is designed for January through March, the period selected for its slower rhythm and restorative pace. Your curator confirms the suite and transfer sequence for your exact dates before anything is booked." },
      { question: "How do I reach Matetsi Victoria Falls?", answer: "Kupona begins in Victoria Falls, Zimbabwe. Ryravel coordinates the private onward transfer to Matetsi Private Reserve; international flights to and from Victoria Falls are not included." },
      { question: "What does the starting investment include?", answer: "The starting investment includes four nights at Matetsi Victoria Falls, all meals and house drinks, game drives, walks, a Zambezi boat cruise, canoeing, fishing, internal transfers, a guided tour of Victoria Falls, laundry, emergency medical evacuation cover, one river-view massage, the Departure Box, and the Ryravel journal." },
      { question: "Can Kupona be designed for a solo traveller?", answer: "Yes. The published starting investment is per person sharing. Tell us that you are travelling alone and your curator will confirm the private solo arrangement and exact investment for your dates." },
    ],
  },
  {
    slug: "runyararo",
    arc: "stillness",
    nights: 4,
    days: 5,
    title: "Runyararo",
    destination: "Hwange National Park · Zimbabwe",
    tagline: "Where the noise cannot follow.",
    description: "A four-night private luxury safari at Somalisa Camp in Hwange National Park, designed around true quiet, unhurried days and the return of internal peace.",
    tags: ["Jan–Mar", "Hwange", "Private stillness safari"],
    price: "$4,950",
    priceNote: "From $4,950 per person sharing · exact departure pricing confirmed at booking",
    image: "/journeys/runyararo/hwange-sunset.webp",
    images: ["/journeys/runyararo/hwange-sunset.webp", "/journeys/runyararo/hwange-leopard.webp"],
    imageAlt: "Acacia trees silhouetted against a golden sunset in Hwange National Park, Zimbabwe",
    seoTitle: "Runyararo: Private Luxury Hwange Safari",
    seoDescription: "A four-night private luxury safari at Somalisa Camp in Hwange National Park, Zimbabwe, designed for stillness and restoration. From $4,950 per person sharing.",
    keywords: ["private luxury Hwange safari", "Somalisa Camp safari", "Hwange National Park luxury safari", "Zimbabwe private safari", "quiet African safari", "luxury safari for mental rest", "restorative Zimbabwe safari", "Stillness Collection"],
    availableMonths: ["January", "February", "March"],
    accommodation: "Somalisa Camp",
    tripOrigin: "Victoria Falls, Zimbabwe",
    phases: ["The Long Way In", "The Veld Goes Quiet", "The Middle of Nowhere", "Peace Is a Place", "The Return"],
    faqs: [
      { question: "When can I take the Runyararo journey?", answer: "This Runyararo edition is designed for January through March, Hwange's quieter green-season window. Rates move slightly from year to year, so your curator confirms the exact departure investment and camp space before anything is booked." },
      { question: "How do I reach Somalisa Camp?", answer: "Runyararo begins in Victoria Falls, Zimbabwe. Ryravel coordinates the onward transfer into Hwange National Park and Somalisa Camp; international flights to and from Victoria Falls are not included." },
      { question: "What does the starting investment include?", answer: "The starting investment includes four nights fully inclusive at Somalisa Camp with all meals, selected drinks and laundry, game drives, walking safaris, night drives in the private concession, park fees, transfers from Victoria Falls, the Departure Box, and the Ryravel journal." },
      { question: "Can Runyararo be designed for a solo traveller?", answer: "Yes. The published starting investment is per person sharing. Tell us that you are travelling alone and your curator will confirm the private solo arrangement and exact investment for your dates." },
    ],
  },
  {
    slug: "utalala",
    arc: "stillness",
    nights: 4,
    days: 5,
    title: "Utalala",
    destination: "South Luangwa National Park · Zambia",
    tagline: "The stillness you can't find at home.",
    description: "A four-night private luxury walking safari at Luwi Bush Camp in South Luangwa, designed to let the mind match the body, one unhurried step at a time.",
    tags: ["May–Nov", "South Luangwa", "Private walking safari"],
    price: "$6,250",
    priceNote: "From $6,250 per person sharing · exact departure pricing confirmed at booking",
    image: "/journeys/utalala/south-luangwa-scops-owl.webp",
    images: ["/journeys/utalala/south-luangwa-scops-owl.webp", "/journeys/utalala/south-luangwa-hippos.jpg", "/journeys/utalala/south-luangwa-dew.webp"],
    imageAlt: "African scops owl resting among leaves in South Luangwa National Park, Zambia",
    seoTitle: "Utalala: Private Luxury South Luangwa Walking Safari",
    seoDescription: "A four-night private luxury walking safari at Luwi Bush Camp in South Luangwa National Park, Zambia. A restorative journey from $6,250 per person sharing.",
    keywords: ["private South Luangwa walking safari", "luxury Zambia walking safari", "Luwi Bush Camp safari", "South Luangwa luxury safari", "Norman Carr walking safari", "restorative African safari", "private Zambia safari", "Stillness Collection"],
    availableMonths: ["May", "June", "July", "August", "September", "October", "November"],
    accommodation: "Luwi Bush Camp",
    tripOrigin: "Lusaka, Zambia",
    phases: ["The Last Road", "The First Walk", "Walking Further", "Stillness, Kept", "The Return"],
    faqs: [
      { question: "When can I take the Utalala journey?", answer: "Utalala is designed for May through November, when the dry-season paths in South Luangwa support walking. July through October is the fullest peak stretch, and your curator confirms the exact departure investment and camp space before anything is booked." },
      { question: "How do I reach Luwi Bush Camp?", answer: "Utalala begins in Lusaka, Zambia. The journey includes return flights between Lusaka and Mfuwe and the onward camp transfers. International flights to and from Lusaka are not included." },
      { question: "How demanding are the walking safaris?", answer: "Walks are guided and paced around the guest rather than a performance target. You should be comfortable walking on natural, uneven ground; share any mobility, health or pace considerations so your curator and the camp can design the right rhythm." },
      { question: "What does the starting investment include?", answer: "The starting investment includes four fully inclusive nights at Luwi Bush Camp, guided walking safaris and game drives, park fees, return Lusaka–Mfuwe flights, the Departure Box, and the Ryravel journal." },
      { question: "Can Utalala be designed for a solo traveller?", answer: "Yes. The published starting investment is per person sharing. Tell us that you are travelling alone and your curator will confirm the private solo arrangement and exact investment for your dates." },
    ],
  },
  { slug: "st6", arc: "stillness", nights: 6, title: "The Return", destination: "Grumeti Reserve", tagline: "Six nights. One camp. One landscape. One uninterrupted descent into stillness.", description: "A singular, guest-paced stay in Grumeti where nothing competes with your own unraveling.", tags: ["Both seasons", "Single camp", "Silent documentary"], price: "$40,000", priceNote: "Green season from $40,000 · Dry season from $50,500", phases: ["Surrender & Unraveling", "Silence & Encounter", "Depth & Integration"] },
  { slug: "st9", arc: "stillness", nights: 9, title: "The Deepening", destination: "Eastern Serengeti · Tarangire", tagline: "Nine nights. Two camps. Two landscapes. A progression from surrender to integration.", description: "The first landscape unravels. The second holds. A deliberate transition turns geography into emotional architecture.", tags: ["Both seasons", "Two camps", "Two landscapes"], price: "$45,800", priceNote: "Green season from $45,800 · Dry season from $58,500", phases: ["The Unraveling", "The Transition", "Grounding & Integration"] },
];

export function arcFor(id) {
  return arcs.find((arc) => arc.id === id);
}

export function journeyFor(slug) {
  return journeys.find((journey) => journey.slug === slug);
}
