import Link from "next/link";
import PolicyPage from "../components/PolicyPage";
import { buildMetadata } from "../seo";

export const metadata = buildMetadata({ title: "Private Journey Booking Terms", description: "How Ryravel proposals, deposits, confirmation, payments and changes work for private journeys.", path: "/terms" });

export default function TermsPage() {
  return <PolicyPage title="A booking, clearly made." intro="The terms that matter most should be understood before you commit. These are our standard booking terms; your written proposal will identify your exact arrangements and any disclosed supplier-specific conditions." updated="23 September 2026">
    <section><h2>Who you are booking with</h2><p>Ryravel is operated by Tourvana Inc, 2261 Market St, San Francisco, CA 94114, United States. Write to <a href="mailto:hello@ryravel.com">hello@ryravel.com</a> with any booking or policy question.</p></section>
    <section><h2>From conversation to confirmation</h2><p>An enquiry, call or draft itinerary is not a booking and does not hold availability. We provide a written proposal with the itinerary, inclusions, exclusions, price, payment dates and any supplier-specific conditions. Please review it before authorising payment.</p><p>The usual deposit is 50% of the agreed journey price. You may instead pay in full. A booking becomes confirmed when we have verified availability, received the 50% deposit or full payment, and sent written confirmation. Payment alone does not confirm unavailable arrangements. If an arrangement cannot be confirmed, we will discuss an alternative or return payment for that unconfirmed booking.</p></section>
    <section><h2>Balance and price</h2><p>The remaining balance is due before the journey begins, on the date stated in your proposal or confirmation. Prices and availability can change until we confirm the booking. After confirmation, a requested change may affect the price; we will explain it before you approve the amendment. Your proposal states what is and is not included, including any international flights.</p></section>
    <section><h2>Changes and cancellations</h2><p>If you need to change or cancel, contact us promptly in writing. Our <Link href="/cancellations">cancellation and refund policy</Link> sets out the standard schedule. Any stricter named supplier condition must be shown to you before payment. We will not silently add a new supplier penalty after you book.</p><p>If a confirmed supplier cannot provide a material part of the journey, we will explain the available replacement, refund or other remedy under your booking and applicable law. We will not simply apply the traveller-cancellation schedule to a supplier-caused change.</p></section>
    <section><h2>During your journey</h2><p>Ryravel provides 24/7 in-travel support by email and direct call. Your confirmation or travel documents will provide the relevant contact details. We select properties and local partners for their suitability to the proposed journey and review the arrangements with you before booking; specific properties and services remain subject to confirmation.</p></section>
    <section><h2>Your preparation</h2><p>You are responsible for valid passports, entry permission or visas, applicable health requirements and suitable travel insurance. We recommend insurance that covers medical care, interruption and cancellation for your circumstances. Tell us about accessibility or other material needs early so we can check what suppliers can accommodate. See <Link href="/travel-information">before you travel</Link>.</p></section>
    <section><h2>Questions and rights</h2><p>If something is not as agreed, tell the local provider and Ryravel as soon as possible so we can try to resolve it while you travel. These terms do not remove consumer rights that cannot lawfully be excluded. For a written response, email <a href="mailto:hello@ryravel.com">hello@ryravel.com</a>.</p></section>
  </PolicyPage>;
}
