import Link from "next/link";
import PolicyPage from "../components/PolicyPage";
import { buildMetadata } from "../seo";

export const metadata = buildMetadata({ title: "Private Journey Booking Terms", description: "How Ryravel proposals, deposits, confirmation, payments and changes work for private journeys.", path: "/terms" });

export default function TermsPage() {
  return <PolicyPage title="A booking, clearly made." intro="The terms that matter most should be understood before you commit. These are our standard booking terms; your written proposal will identify your exact arrangements and any disclosed supplier-specific conditions." updated="25 September 2026">
    <section><h2>Who you are booking with</h2><p>Ryravel is operated by Tourvana Inc, 2261 Market St, San Francisco, CA 94114, United States. Write to <a href="mailto:hello@ryravel.com">hello@ryravel.com</a> with any booking or policy question.</p></section>
    <section><h2>From conversation to confirmation</h2><p>An enquiry, call or draft itinerary is not a booking and does not hold availability. We provide a written proposal and service agreement with the itinerary, inclusions, exclusions, price, payment dates and any supplier-specific conditions. Please review them before authorising payment.</p><p>A 50% deposit is required to secure the journey. If the booking is made within 45 days of departure, full payment is required instead. A booking is confirmed once you have signed the service agreement, we have verified availability and received cleared payment of the required deposit or full amount, and we have sent written confirmation. Initiating a payment alone does not confirm unavailable arrangements. If an arrangement cannot be confirmed, we will discuss an alternative or return payment for that unconfirmed booking.</p></section>
    <section><h2>Balance and price</h2><p>For bookings made more than 45 days before departure, the remaining balance is due 30 days before departure. For bookings made within 45 days, the full price is due at booking. Your proposal and confirmation will show the exact amount and date. Prices and availability can change until we confirm the booking. After confirmation, a requested change may affect the price; we will explain it before you approve the amendment.</p><p>Journey prices exclude international flights, visa fees and personal travel insurance unless your written proposal expressly includes them. We can quote flight booking, visa assistance and travel insurance separately as optional add-ons, based on your departure country and itinerary. The written proposal states every inclusion, exclusion and add-on price before you commit.</p></section>
    <section><h2>Changes and cancellations</h2><p>You can request an amendment until 15 days before departure. Ryravel charges no amendment fee for changes requested more than 30 days before departure, although a fare or supplier price difference may apply. For requests 15–30 days before departure, a fee may apply based on supplier costs. We will tell you the exact cost before making any change; an amendment is not final until suppliers accept it and we confirm it in writing.</p><p>If you need to cancel, contact us promptly in writing. Our <Link href="/cancellations">cancellation and refund policy</Link> sets out the standard schedule, including the different outcomes for cancellations received 45 or more days, 30–44 days and fewer than 30 days before departure. Any stricter named supplier condition must be shown to you before payment. We will not silently add a new supplier penalty after you book.</p><p>If a confirmed supplier cannot provide a material part of the journey, we will explain the available replacement, refund or other remedy under your booking and applicable law. We will not simply apply the traveller-cancellation schedule to a supplier-caused change or make a material substitution without first discussing it with you, except where an urgent safety issue requires immediate action.</p></section>
    <section><h2>During your journey</h2><p>Ryravel provides 24/7 in-travel support by email and direct call. Your confirmation or travel documents will provide the relevant contact details. We select properties and local partners for their suitability to the proposed journey and review the arrangements with you before booking; specific properties and services remain subject to confirmation.</p></section>
    <section><h2>Your preparation</h2><p>You are responsible for valid passports, entry permission or visas, applicable health requirements and suitable travel insurance, even if you ask us to assist with an application or source cover. Visa decisions belong to the relevant authority; insurance eligibility, coverage and claims are determined by the insurer and policy terms. Tell us about accessibility or other material needs early so we can check what suppliers can accommodate. See <Link href="/travel-information">before you travel</Link>.</p></section>
    <section><h2>Questions and rights</h2><p>If something is not as agreed, tell the local provider and Ryravel as soon as possible so we can try to resolve it while you travel. These terms do not remove consumer rights that cannot lawfully be excluded. For a written response, email <a href="mailto:hello@ryravel.com">hello@ryravel.com</a>.</p></section>
  </PolicyPage>;
}
