import Link from "next/link";
import PolicyPage from "../components/PolicyPage";
import { buildMetadata } from "../seo";

export const metadata = buildMetadata({ title: "Journey Cancellations & Refunds", description: "Ryravel's standard journey cancellation schedule, supplier exceptions, amendments and refund process.", path: "/cancellations" });

export default function CancellationsPage() {
  return <PolicyPage title="If plans change." intro="Our standard cancellation schedule is below. The written proposal will identify any different non-refundable supplier commitments before you authorise payment." updated="25 September 2026">
    <section><h2>Standard traveller cancellation schedule</h2><p>Tell us in writing at <a href="mailto:hello@ryravel.com">hello@ryravel.com</a>. We use the date we receive your message to determine the applicable period. These terms apply after a booking is confirmed, except where your written proposal specifically identifies a different supplier condition before payment or applicable law requires a different outcome.</p>
      <div className="policy-table" role="table" aria-label="Standard cancellation schedule"><div role="row"><strong role="columnheader">When we receive your cancellation</strong><strong role="columnheader">Standard refund</strong></div><div role="row"><span role="cell">45 days or more before departure</span><span role="cell">Payments received, less a US $300 administration and processing fee.</span></div><div role="row"><span role="cell">30–44 days before departure</span><span role="cell">50% of payments received.</span></div><div role="row"><span role="cell">Fewer than 30 days before departure</span><span role="cell">No standard cash refund. We will ask suppliers whether any value can be transferred as a credit; this is not guaranteed.</span></div></div>
      <p>The standard schedule does not mean an additional automatic forfeiture of the 50% deposit. If a flight fare, property, charter or other named arrangement has stricter cancellation terms, we will show those terms and their effect in your proposal before you pay. We will not silently add supplier penalties on top of the schedule above.</p></section>
    <section><h2>Amendments and unused services</h2><p>You may request a date, route or traveller amendment until 15 days before departure. For requests more than 30 days out, Ryravel charges no amendment fee; any fare or supplier price difference is still payable. For requests 15–30 days out, supplier change costs may apply. We will explain the exact amount before you approve a change. Requests fewer than 15 days before departure cannot be handled as standard amendments; contact us and we will explain any available options. An amendment is not confirmed until the relevant suppliers accept it and we confirm it in writing. A service you choose not to use after travel starts may not be refundable; we will seek any recoverable supplier value where possible.</p></section>
    <section><h2>If Ryravel or a supplier changes the journey</h2><p>We will tell you promptly about a material change and the available alternatives, refund or other remedies applicable to your booking and governing law. We seek your approval before making a material substitution, except where immediate action is necessary for safety. The proposal and confirmation identify the relevant arrangements. We will not treat the traveller-cancellation table as an automatic answer when a supplier cannot provide a confirmed service.</p></section>
    <section><h2>How refunds are handled</h2><p>We confirm the applicable calculation and any documented supplier exception in writing. Approved refunds are returned to the original payment method where practicable. Timing can depend on payment processors and suppliers; we will provide an update rather than promise an unverified fixed processing time. Statutory rights are not excluded by this page.</p><p>See also our <Link href="/terms">booking terms</Link> and <Link href="/travel-information">travel information</Link>.</p></section>
  </PolicyPage>;
}
