import Link from "next/link";
import styles from "./KimbilioJourney.module.css";
import { JourneyAvailability, JourneyFaqs, JourneyProofSection, StillnessAlternatives } from "./JourneyPlanning";

const days = [
  { number: "01", title: "The World Falls Away", route: "Southern Serengeti · Night 1", paragraphs: ["The charter landed us straight onto the southern plains, no town in between to ease into it. The orientation drive put more raw life in front of me than I usually let myself sit with in a whole year, not because I avoid nature, but because I avoid anything that asks me to actually feel something for longer than a sentence. No signal that night, and I noticed the calving season sounds gentler than I expected, less dramatic than I'd braced for, which somehow made it harder to make light of."] },
  { number: "02", title: "The Plains in Full Life", route: "Southern Serengeti · Night 2", paragraphs: ["A dawn drive put us close enough to a herd in labour that I could hear it, and I caught myself reaching for a joke about the smell before I stopped and just let it be what it was, a birth, nothing to lighten. We rested through the heat, walked the short-grass plains with a tracker in the afternoon, and that evening my guide talked about why this particular season is the most honest version of the migration, nothing dramatized, nothing softened. I found myself, for once, not turning it into something funnier than it was."] },
  { number: "03", title: "Ndutu, the Calving Plains", route: "Ndutu · Night 3", paragraphs: ["The landscape flattened out until the wildebeest reached the horizon in every direction, which was somehow more unsettling than a dramatic view would have been. A cheetah hunt in the afternoon, close, no soundtrack, no cutaway. Dinner by the fire, flamingos calling from the lake at dusk, and for once I didn't fill the quiet at the table with anything."] },
  { number: "04", title: "The Hunt and the Birth", route: "Ndutu · Night 4", paragraphs: ["A dawn drive put a lion pride managing a kill and a wildebeest giving birth within the same two-hour stretch, and my guide didn't lean into either one as more important than the other, they were just both happening, plainly. I noticed I didn't reach for a comment to soften either scene, which isn't like me at all, usually I'd have something to say by now. We rested through the heat, walked the plains in the afternoon, and that evening my guide asked what had surprised me most about what I'd seen. I gave him an honest answer instead of a funny one, which surprised me more than the actual question did."] },
  { number: "05", title: "The Morning You Don't Expect", route: "Ndutu · Night 5", paragraphs: ["Nothing about today had been mentioned to me in advance. A tracker who's worked these plains for over twenty years turned up in place of my usual guide, no explanation given beyond that the day was his to design. I usually fill unfamiliar silences with something to say, and he didn't leave much room for that, just quiet, precise attention to where the light and the wind were pointing him. By the afternoon I'd stopped trying to narrate the day to myself and just watched what he was watching.", "A woman with a camera caught me mid-sentence, some half-formed joke I hadn't finished, and instead of asking me to reset she just kept the shutter going. The herd stayed behind me the whole time. The pictures reached me three days after I got home, and in most of them I wasn't smiling in the way I usually perform for a camera, I just looked like someone actually there. I sat with that longer than I expected to.", "Back at camp, a basket was waiting at the tent, and the note inside said the one thing I hadn't said to anyone, including myself, when I booked this trip, that I'd come here to disappear and was starting to be found. I read it twice and didn't make a joke about it either time, which felt like its own small event. My guide joined for the first drink at dinner that night, and I let the conversation stay slow instead of steering it somewhere lighter."] },
  { number: "06", title: "The Crater", route: "Ngorongoro Crater Rim · Night 6", paragraphs: ["The short flight to Ngorongoro put an ancient, contained world in front of me after days of open, abundant life, and I felt the shift as something closer to relief than I expected. Rest on arrival, an optional walk along the rim, and dinner that evening ran slower than any meal all week. I didn't try to hurry the conversation along the way I usually would."] },
  { number: "07", title: "Last Morning. The Return.", route: "Ngorongoro · Departure", paragraphs: ["A dawn walk on the rim as the crater slowly revealed itself below. The box was presented over breakfast, Maasai beadwork inside it, a pressed wildflower from the calving plains, oils pressed locally, and a handwritten field note from my guide about what he'd noticed in me over six nights, things I'd been deflecting from since Day One that he'd apparently clocked anyway. Underneath it was a sealed letter, and I opened it without deflecting from whatever it was going to say, which is not how I usually open anything that might actually mean something. I read it once, straight through, no joke ready at the end of it for once. What it said is mine to keep. What I'll say is that I didn't need to make it lighter to get through reading it. The private vehicle to the airport was quiet, and I let it stay that way."] },
];

function Day({ day }) {
  return <article className={styles.day}><div className={styles.dayMeta}><span>Day {day.number}</span><h3>{day.title}</h3><small>{day.route}</small></div><div className={styles.dayCopy}>{day.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></article>;
}

export default function CalvingSeasonJourney({ journey }) {
  const requestHref = `/request?journey=${journey.slug}&name=${encodeURIComponent(journey.title)}&destination=${encodeURIComponent(journey.destination)}&nights=${journey.nights}&price=${encodeURIComponent(journey.price)}`;
  const callHref = `${requestHref}&conversation=private-call`;

  return <main className={`${styles.page} ${styles.calvingSeason}`}>
    <section className={styles.hero}>
      <img src={journey.image} alt={journey.imageAlt} width="1920" height="1280" fetchPriority="high" />
      <div className={styles.heroShade} aria-hidden="true" />
      <div className={styles.heroTop}><Link href="/journeys/stillness">← The Stillness Collection</Link><span>Disconnected · The Return</span></div>
      <div className={styles.heroBody}><p className={styles.eyebrow}>Calving Season · Southern Serengeti · January to March</p><h1>The Calving Season</h1><p className={styles.meaning}>Six nights. Three landscapes. Room for what is real.</p><h2>Nothing to make lighter.</h2></div>
      <dl className={styles.facts}><div><dt>Duration</dt><dd>6 Nights, 7 Days</dd></div><div><dt>Location</dt><dd>Southern Serengeti · Ndutu · Ngorongoro</dd></div><div><dt>From</dt><dd>$11,075 / person</dd></div></dl>
    </section>

    <section className={styles.opening}><div className={styles.openingMain}><span className={styles.sectionLabel}>Why this journey</span><h2>Birth and death sit in the same frame.<br />Neither asks to be softened.</h2><div className={styles.openingCopy}><p>I'm the one who makes it light. Someone tells me something hard and I find the joke in it within about four seconds, not because I don't feel it, but because feeling it out loud has never come naturally to me. I've been told I'm easy to be around. I've started to suspect that's partly because I never let anyone get close enough to see the parts that aren't easy.</p><p>Six nights. Two on the plains to settle in, three at Ndutu where the calving is at its most concentrated, one at the crater to close. No Wi-Fi at the mobile camp, and no way to deflect from what's actually in front of you, birth and death sitting in the same two-hour window, neither one softened for an audience.</p></div></div><aside className={styles.openingAside}><span>In one sentence</span><p>The calving plains ask you to stay with what is there.</p></aside></section>

    <section className={styles.fit}><div><span className={styles.sectionLabel}>Who this is for</span><h2>You are easy to be around.<br />Harder to really know.</h2></div><div><p>For the traveller who can make any room feel lighter, but wants the rare permission to stop turning every difficult thing into a joke.</p><ul><li>You want a private wildlife journey with room to feel, not a checklist of sightings.</li><li>You can sit with the unscripted reality of the calving plains.</li><li>You want time at Ndutu and a deliberate close at the crater.</li></ul><Link href={requestHref}>Ask a curator about this journey →</Link></div></section>

    <section className={styles.itinerary} aria-labelledby="calving-itinerary"><header><span className={styles.sectionLabel}>The journey · Land & Open</span><h2 id="calving-itinerary">Seven days of<br /><em>staying with what is real.</em></h2></header>
      {days.slice(0, 2).map((day) => <Day day={day} key={day.number} />)}
      <section className={styles.signature}><span>Phase Two · Nights 3–5</span><h2>Ndutu, the Heart of the Calving.</h2><p>The camp sits on the edge of Lake Ndutu, surrounded by the short-grass plains where calving density is highest. Cheetahs, lions, leopards, and no Wi-Fi to look away toward.</p></section>
      {days.slice(2, 5).map((day) => <Day day={day} key={day.number} />)}
      <figure className={styles.landscape}><img src="/journeys/calving-season/camp-hospitality.webp" alt="A safari lodge team member carrying guest supplies along a path beside camp" width="1920" height="1280" loading="lazy" /><figcaption>The human care behind a wilderness stay · guest comforts prepared at camp.</figcaption></figure>
      <blockquote className={styles.pullQuote}>“The ecosystem does not soften its truths for an audience. Birth and death sit in the same frame, and neither one asks to be made lighter.”</blockquote>
      <section className={styles.signature}><span>Phase Three · Night 6 · Day 7 departure</span><h2>Close &amp; Carry.</h2><p>After the open plains, the crater gives the journey a quieter frame before the return.</p></section>
      {days.slice(5).map((day) => <Day day={day} key={day.number} />)}
    </section>

    <section className={styles.season}><div><span className={styles.sectionLabel}>The calving window</span><h2>January through March.</h2><p>February is the peak calving period in this journey design. The exact movement of wildlife, available camps and departure price are confirmed for your dates; no particular sighting can be promised.</p></div><div className={styles.months} aria-label="Calving Season travel window">{["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"].map((month, index) => <span className={index < 3 ? styles.openMonth : ""} key={month}>{month}</span>)}<p className={styles.monthLegend}><b>Open</b> January, February and March<br />March departures from $11,075 per person</p></div></section>
    <JourneyAvailability journey={journey} title="When would you meet the calving plains?" copy="Tell us your preferred dates and party. We will confirm the camp, internal flights and exact journey investment with you personally." openMonths={journey.availableMonths} closedNote="This calving-season edition is available January through March only." />
    <section className={styles.investment}><div><span className={styles.sectionLabel}>Investment</span><h2>Six nights.<br /><em>The calving plains.</em><br />Everything included.</h2></div><div className={styles.price}><small>From · March departures</small><strong>$11,075</strong><span>/ person</span><p>International flights are not included. All internal flights, camp transfers, game drives, the senior tracker day, Signature Rituals and Ryravel host support are included. February is peak calving, the highest concentration of births and predator activity. January–March pricing and final inclusions are confirmed in your personal proposal.</p><div className={styles.priceActions}><Link href={requestHref}>Begin the conversation →</Link><Link className={styles.secondaryAction} href={callHref}>Request a private call</Link></div><small className={styles.reassurance}>A curator responds personally within one business day. Nothing is booked until you are ready.</small></div></section>
    <JourneyProofSection />
    <JourneyFaqs journey={journey} />
    <section className={styles.nextSteps}><div><span className={styles.sectionLabel}>What happens next</span><h2>A private conversation.<br />Then the plains.</h2></div><ol><li><span>01</span><div><h3>Tell us what drew you here</h3><p>Share your preferred month, party and what you hope to make space for.</p></div></li><li><span>02</span><div><h3>Speak with your curator</h3><p>We confirm camp and flight space, pace and exact investment.</p></div></li><li><span>03</span><div><h3>Receive a considered direction</h3><p>One personal journey proposal, with no booking until you are ready.</p></div></li></ol><Link href={requestHref}>Plan The Calving Season privately →</Link></section>
    <StillnessAlternatives currentSlug={journey.slug} />
    <section className={styles.closing}><div className={styles.backLinks}><Link href="/journeys">← Back to all journeys</Link><Link href="/journeys/stillness">The Stillness Collection</Link></div><blockquote>“I've spent years making everything lighter than it was. Out there, nothing needed me to. So, for once, I didn't.”</blockquote><p>Ryravel · The Calving Season</p></section>
  </main>;
}
