import Link from "next/link";

const months = [
  ["January", "shoulder"], ["February", "shoulder"], ["March", "low"], ["April", "low"],
  ["May", "low"], ["June", "shoulder"], ["July", "high"], ["August", "high"],
  ["September", "high"], ["October", "high"], ["November", "shoulder"], ["December", "shoulder"],
];

export default function ExhaustedRestorationNine() {
  return (
    <main className="restoration-page">
      <section className="restoration-hero">
        <img src="/journeys/rn9/exhausted-serengeti-camp.webp" alt="A tented camp beneath a dramatic sky on the Serengeti plains" />
        <div className="restoration-hero-overlay" />
        <div className="restoration-hero-content">
          <p className="restoration-eyebrow">The Exhausted Traveller&apos;s Return</p>
          <p className="restoration-collection">Exhausted → Relief · Beach, Then Wilderness</p>
          <h1>Exhausted, The Restoration</h1>
          <p className="restoration-hero-em">I run three group chats, two calendars, and a household. Nobody asked me to. Nine nights, and for once, nothing needed managing.</p>
          <div className="restoration-meta">
            <p>Duration <span>9 Nights</span></p>
            <p>Destinations <span>Zanzibar · Serengeti</span></p>
            <p>From <span>$26,611 / person</span></p>
          </div>
        </div>
      </section>

      <section className="restoration-intro"><div>
        <p className="restoration-intro-lead">I am the one who remembers everyone&apos;s allergies, confirms the reservation twice, packs the spare charger nobody thinks to ask for. Somewhere along the way that became my whole personality, and I stopped noticing I&apos;d never once been the person being looked after.</p>
        <p>Four nights on the coast, four in the bush, two back where I started. I brought a small notebook out of habit, fully intending to keep track of things. By the middle of the trip I couldn&apos;t tell you where it ended up, and for the first time in longer than I want to admit, that didn&apos;t bother me at all.</p>
      </div></section>

      <div className="restoration-content">
        <section className="restoration-phase">
          <header><p>Phase One</p><h2>Dissolve</h2><span>Nights 1 – 4 · Zanzibar</span><strong>The Residence Zanzibar, Royal Zanzibar Beach Resort, or Zuri Zanzibar <em>· coastal properties</em></strong></header>
          <article className="restoration-day"><p className="day-number">Day One</p><h3>You Are Here Now</h3><small>Staying: The Residence Zanzibar / Royal Zanzibar Beach Resort / Zuri Zanzibar</small><p>I&apos;d already mentally rebooked the connecting flight twice before we landed, out of pure reflex, before I remembered nobody was waiting on me to fix anything this week. The room was ready the second we walked in, no waiting at a desk, no form to sign twice. A cold towel appeared before I&apos;d asked for one. A coconut, cut and ready, no straw wrapper to throw away because there wasn&apos;t one. I sat with that small absence of clutter longer than I expected to. Dinner was quiet, and for once I didn&apos;t check whether anyone else at the table needed anything before I let myself order.</p></article>
          <article className="restoration-day"><p className="day-number">Day Two</p><h3>The Body First</h3><p>No alarm, which meant I woke up at my usual time anyway and lay there for twenty minutes negotiating with myself about whether that counted as failing. It didn&apos;t. Breakfast came to the terrace, and the ocean did what oceans do, going about its business whether or not I was watching. Two hours of clove and coconut oil on a table found the exact spot between my shoulders where I carry every unanswered email, and worked it loose without me having to explain what it was. I spent the afternoon doing the thing I&apos;m worst at, absolutely nothing, on a hammock I kept meaning to get out of and never did.</p></article>
          <article className="restoration-day"><p className="day-number">Day Three</p><h3>The Island Speaks Softly</h3><p>My guide walked us to the house where Freddie Mercury was born, a plain building I would have missed without him, and told the story like he&apos;d never told it before, even though I suspected he had, daily, for years. Lunch was street food dressed up just enough at Forodhani Gardens, and I ate standing at the counter instead of finding a table, which for me passed as an act of rebellion. The afternoon was a nap I hadn&apos;t planned and didn&apos;t apologize to myself for. That evening, on the dhow, someone else poured the champagne, someone else timed the sunset, and I just sat there letting it happen to me instead of around me.</p></article>
          <article className="restoration-day"><p className="day-number">Day Four</p><h3>Sand, Sea, Nothing Else</h3><p>A full day with no plan attached to it, which I found more disorienting than relaxing at first. I went out to Mnemba anyway, mostly for something to do with my hands, and ended up floating over the reef for far longer than I meant to, watching a school of fish reorganize itself around me without any of us deciding to. Nobody called to check on lunch. Nobody needed me to confirm anything. I noticed, around three in the afternoon, that I&apos;d gone a full day without once being the one who remembered something for somebody else.</p></article>
          <aside className="restoration-signature"><p>Ryravel Signature · The Beach Gift · Day 4</p><h3>&quot;You came here exhausted. Today, you don&apos;t have to be anything at all.&quot;</h3><span>I spotted the basket from a distance and, out of habit, assumed it was something I&apos;d need to move or tidy or return to someone. It was mine. The note inside said the one thing nobody in my life had thought to say to me directly, that I didn&apos;t owe today anything. I sat with the kaftan in my lap for a minute before I even put it on, turning the note over once like there might be more written on the back. There wasn&apos;t. Dinner that night was set right there on the sand, and for the first time all week I let someone else decide when the evening was over.</span></aside>
        </section>

        <figure className="restoration-image"><img src="/journeys/rn9/exhausted-serengeti-land-rover.webp" alt="A safari vehicle beneath an acacia tree at sunset in the Serengeti" /><figcaption>Serengeti · Tanzania</figcaption></figure>

        <section className="restoration-phase">
          <header><p>Phase Two</p><h2>Awaken</h2><span>Nights 5 – 8 · Serengeti</span><strong>andBeyond Serengeti Under Canvas or Nomad Serengeti Camp <em>· tented camps</em></strong></header>
          <article className="restoration-day"><p className="day-number">Day Five</p><h3>The Plains Open</h3><small>Staying: andBeyond Serengeti Under Canvas / Nomad Serengeti Camp</small><p>From the air the coast just stopped, replaced by grass that didn&apos;t seem to end anywhere in particular. My guide and a Maasai tracker were waiting when we landed, and within ten minutes he&apos;d clocked, without me saying it, that I was the type who needed a reason to sit still. So he gave me one: a herd of elephants working their way across the plain, unbothered, taking their time in a way I found almost offensive to watch at first. We ended the day at a kopje with a drink in hand, and by the second sip I&apos;d stopped scanning the horizon for anything in particular and just let it be a horizon.</p></article>
          <article className="restoration-day"><p className="day-number">Day Six</p><h3>The Great Silence</h3><p>The one early start of the whole trip, and I was oddly grateful for it, an alarm I hadn&apos;t set myself, for once. Golden hour turned the grass a colour I don&apos;t have a name for. Back at camp for a bush breakfast, then real rest through the heat of the day, no negotiating with myself about whether I&apos;d earned it. In the afternoon I walked with a tracker who moved so quietly I kept losing track of him a few paces ahead, reading tracks in the dirt I wouldn&apos;t have noticed were there. Dinner that night was under more stars than I&apos;ve ever tried to count, hurricane lamps doing just enough work to see the plate in front of me.</p></article>
          <article className="restoration-day"><p className="day-number">Day Seven</p><h3>Above the Earth</h3><p>Someone knocked while it was still dark, no explanation given, and I&apos;d learned enough by then not to ask for one.</p></article>
          <aside className="restoration-surprise"><p>The Ryravel Surprise · Not disclosed in advance</p><span>The balloon lifted before the sun did, and for a while there was nothing to manage, nothing to time, nothing to hand to anyone. Just wildebeest scattered across the plain like something spilled and left exactly where it landed. I didn&apos;t reach for my phone once, mostly because I&apos;d left it in the tent without noticing I had. We came down in tall grass to a table already set, champagne going warm faster than anyone cared to drink it, and I laughed at something I can&apos;t even remember now, loudly, the kind of laugh I usually save for people I&apos;ve known for years.</span></aside>
          <aside className="restoration-signature"><p>Ryravel Signature · The Photoshoot · Day 7</p><h3>Not a tourist photo. Something closer to proof.</h3><span>I was mid-complaint about the dust in my boots when the photographer started shooting, and she didn&apos;t stop me or ask me to fix my face, she just let the complaint happen and caught it anyway. Forty minutes, and I only remembered the camera was there twice. The pictures showed up four days after I was home, back at my desk, in the middle of rearranging someone else&apos;s calendar, and I stopped what I was doing to look properly. I looked like someone mid-laugh, not mid-task, for what might have been the first photo of me like that in years.</span></aside>
          <article className="restoration-day"><p className="day-number">Day Eight</p><h3>The Last Morning Wild</h3><small>Return stay begins tonight: Baraza Resort &amp; Spa</small><p>My guide found the thing I hadn&apos;t yet seen, a cheetah stretched flat on a termite mound, entirely unimpressed by our presence. Then the flight back, and by the time we landed I could feel both the salt and the dust on my skin at once, which felt like proof of something, though I couldn&apos;t say what. Dinner that evening had the ocean back in view, and I noticed I was tired in a completely different way than the tired I&apos;d arrived with.</p></article>
        </section>

        <blockquote>&quot;You do not go from lions to a departure gate. There has to be somewhere quieter to land first.&quot;</blockquote>

        <section className="restoration-phase">
          <header><p>Phase Three</p><h2>Return</h2><span>Nights 9 – 10 · Zanzibar</span><strong>Baraza Resort &amp; Spa <em>· spa-first, Bwejuu Beach</em></strong></header>
          <article className="restoration-day"><p className="day-number">Day Nine</p><h3>Integration</h3><small>Staying: Baraza Resort &amp; Spa, Bwejuu Beach</small><p>The longest treatment of the trip, and partway through I realized I&apos;d stopped mentally drafting the email I&apos;d normally be drafting in a moment like this. Afterward I walked the beach and bought a small carved elephant from a stall I almost didn&apos;t stop at, mostly because the woman running it refused to let me walk past without at least holding it first. It&apos;s on my desk now. That evening&apos;s dinner had a toast attached to it, my host said something brief and genuine and then stepped back, and a journal was waiting at my seat that I didn&apos;t open, not because I was avoiding it, but because I wanted to write in it once I actually had something worth saying.</p></article>
          <article className="restoration-day"><p className="day-number">Day Ten</p><h3>Late Checkout. The Return Begins.</h3><p>Breakfast at whatever pace I felt like, checkout at one, no clock-watching, a habit I&apos;d apparently picked up somewhere in the last nine days without noticing. A box was handed to me at the door, and I caught myself immediately calculating how it would fit in my carry-on before I stopped and just let someone else worry about that. Cold water in the car. Flowers I didn&apos;t ask for and didn&apos;t need to thank anyone for, because the thanking had already been built in. A letter went straight into the outer pocket of my bag, unread, on purpose.</p></article>
          <aside className="restoration-signature"><p>Ryravel Signature · The Departure Box · Day 10</p><h3>What I actually carried home.</h3><span>I read the letter at the gate, standing, because sitting still to read it felt like it needed more ceremony than I had patience for right then. What it said is mine to keep. What I noticed, closing it, was that I hadn&apos;t once reached for my notebook that morning to write down something I needed to remember to do. Nine nights earlier I&apos;d have had a list running before the seatbelt sign turned off. Instead I stood there with an empty notebook I never once opened, and for the first time in longer than I can place, being unprepared for what came next didn&apos;t feel like a problem I needed to solve.</span></aside>
        </section>
      </div>

      <section className="restoration-hotels"><div><p className="section-label">Where You Stay</p><h2>Coast, bush, coast again.</h2><div className="restoration-hotel-grid restoration-hotel-grid-three">
        <article><span>Zanzibar · Coast</span><h3>The Residence Zanzibar, Royal Zanzibar Beach Resort, or Zuri Zanzibar</h3><em>Choice of coastal property</em><strong>Nights 1–4</strong></article>
        <article><span>Serengeti · Plains</span><h3>andBeyond Serengeti Under Canvas or Nomad Serengeti Camp</h3><em>Tented camp, central plains</em><strong>Nights 5–8</strong></article>
        <article><span>Zanzibar · Coast</span><h3>Baraza Resort &amp; Spa</h3><em>Spa-first · Bwejuu Beach</em><strong>Nights 9–10</strong></article>
      </div></div></section>

      <section className="restoration-dates"><div><p className="section-label">Travel Dates</p><h2>When would you begin?</h2><p>This journey runs year-round. Pricing shifts by season, not by experience quality, so tell us your preferred window and we&apos;ll confirm exact camp and villa availability before anything is booked.</p><form action="/request" method="get"><label>Preferred start date<input type="date" name="start-date" /></label><label>Travelling as<select name="party" defaultValue="2 people sharing"><option>2 people sharing</option><option>Solo traveller</option><option>3–4 people</option><option>5+ people</option></select></label><input type="hidden" name="journey" value="Exhausted, The Restoration" /><button type="submit">Check availability</button></form><p className="restoration-seasons"><b>High</b> July, August, September, October &nbsp;&nbsp; <b>Shoulder</b> January, February, June, November, December &nbsp;&nbsp; <b>Low / Green</b> March, April, May</p></div></section>

      <section className="restoration-price"><div><div><p className="section-label">Investment</p><h2>Nine nights. Coast and bush, in equal measure.</h2><p>International flights not included. Domestic flights between Zanzibar and Seronera, all transfers, experiences, meals where indicated, Signature Rituals, and Ryravel host support are included.</p></div><div><small>From</small><strong>$26,611</strong><span>per person · prices vary by season</span><Link className="button button-red" href="/request?journey=Exhausted%2C%20The%20Restoration">Begin the conversation →</Link><Link className="button button-outline-dark" href="/journeys">All journeys</Link></div></div></section>

      <section className="restoration-months"><div><p className="section-label">Prices by Month</p><h2>Exhausted, The Restoration · 9 Nights · Zanzibar + Serengeti</h2><p>International flights are not included. Prices are per person based on two people sharing. All 12 months are available. Prices vary by season, not by experience quality.</p><div className="restoration-month-grid">{months.map(([month, season]) => <article className={season} key={month}><span>{month}</span></article>)}</div><p className="restoration-month-legend">High &nbsp;July · August · September · October&nbsp;&nbsp;&nbsp; Shoulder &nbsp;January · February · June · November · December&nbsp;&nbsp;&nbsp; Low &nbsp;March · April · May</p></div></section>

      <section className="restoration-closing"><Link href="/journeys">← Back to all journeys</Link><p>&quot;I came here still keeping everyone else&apos;s list.<br />I went home without needing to check it once.&quot;</p><span>, Ryravel · Stillness is the only luxury left.</span></section>
    </main>
  );
}
