import Link from "next/link";

const months = [
  ["January", "shoulder"], ["February", "shoulder"], ["March", "low"], ["April", "low"],
  ["May", "low"], ["June", "shoulder"], ["July", "high"], ["August", "high"],
  ["September", "high"], ["October", "high"], ["November", "shoulder"], ["December", "shoulder"],
];

export default function ExhaustedRestoration() {
  return (
    <main className="restoration-page">
      <section className="restoration-hero">
        <img src="/journeys/ex6/exhausted-ngorongoro-sunset.webp" alt="Sunset over the Ngorongoro landscape from a private lodge deck" />
        <div className="restoration-hero-overlay" />
        <div className="restoration-hero-content">
          <p className="restoration-eyebrow">The Exhausted Traveller&apos;s Return</p>
          <p className="restoration-collection">Exhausted → Relief · The Complete Arc</p>
          <h1>Exhausted, The Restoration</h1>
          <p className="restoration-hero-em">I arrived heavy with everything my life had asked of me. Eleven nights later, I understood what it means to put something down.</p>
          <div className="restoration-meta">
            <p>Duration <span>11 Nights</span></p>
            <p>Destinations <span>Zanzibar · Serengeti · Ngorongoro</span></p>
            <p>From <span>$43,500 / person</span></p>
          </div>
        </div>
      </section>

      <section className="restoration-intro">
        <div>
          <p className="restoration-intro-lead">There is a particular kind of tired that doesn&apos;t show up on a scan. You just carry it, in your jaw, your shoulders, the way you answer the phone before it&apos;s finished ringing. I&apos;d been carrying mine for so long I&apos;d stopped noticing the weight of it, until the plane doors opened in Zanzibar and the heat hit me and, for no reason I could explain, I wanted to cry.</p>
          <p>Twelve days. Four on the coast, three on the plains, three at the crater rim, two back where I started. Nobody told me why it was built that way. I only understood it in hindsight, the way you understand a good piece of music after it&apos;s ended, when the shape of the whole thing finally makes sense.</p>
        </div>
      </section>

      <div className="restoration-content">
        <section className="restoration-phase">
          <header><p>Phase One</p><h2>Dissolve</h2><span>Nights 1 – 4 · Zanzibar</span><strong>Baraza Resort &amp; Spa <em>· spa-first, Bwejuu Beach</em></strong></header>
          <article className="restoration-day"><p className="day-number">Days One &amp; Two</p><h3>Arrive. The Body First.</h3><small>Staying: Baraza Resort &amp; Spa, Bwejuu Beach</small><p>The car was waiting when I came through customs, and the driver didn&apos;t ask how my flight was. He just drove, windows down, and let the warm air do the talking. Nobody handed me a schedule. At the villa, a coconut sat sweating on the table next to a card in handwriting I didn&apos;t recognize yet, and somewhere close by, jasmine. I ran a bath I didn&apos;t need and lay in it until the water went cold, and that was the whole of my first evening. I hadn&apos;t done nothing, actual nothing, in years.</p><p>I woke up on my own the next morning, which felt like a small scandal. Breakfast came out to the terrace while the tide crept back in over the sand, close enough that I could hear it before I could see it move. At midday a woman named Fatma pressed clove oil into my shoulders for two hours and found, without me saying anything, exactly where I&apos;d been holding on the tightest. I didn&apos;t talk much. She didn&apos;t need me to. By the time she finished, my hands felt like they belonged to someone who wasn&apos;t in a hurry anymore.</p></article>
          <article className="restoration-day"><p className="day-number">Day Three</p><h3>The Island Speaks Softly</h3><p>Stone Town moves at whatever speed you bring into it, and mine, that morning, was close to a standstill. My guide let me stop wherever I wanted, in front of a spice stall, in the shade of the old Omani fort, at a doorway carved with something neither of us could translate. We ate lunch on a rooftop cooked by a woman who has fed her neighbours the same way for thirty years, pilau, urojo, a fish caught that same morning, and she scolded me, gently, for not taking seconds. That evening a dhow carried us out past the harbour, and somewhere around the third glass of champagne, watching the sun go down the way it only seems to over water, I noticed I&apos;d stopped checking the time.</p></article>
          <article className="restoration-day"><p className="day-number">Day Four</p><h3>Sand, Sea, Nothing Else</h3><p>The water off Mnemba was so clear it barely felt like swimming through anything at all. A turtle drifted past close enough to touch, unbothered, and I floated there watching it work the reef until my fingers pruned. Nobody radioed to check on me. Nobody would, for the rest of the day, and that quiet started to feel less like being forgotten and more like being trusted to look after myself for once.</p></article>
          <aside className="restoration-signature"><p>Ryravel Signature · The Beach Gift · Day 4</p><h3>&quot;You came here exhausted. Today, you don&apos;t have to be anything at all.&quot;</h3><span>There was a basket waiting on my spot on the sand, and for a second I thought I&apos;d wandered onto someone else&apos;s afternoon. It wasn&apos;t. Inside, a kaftan in exactly my size, and a note that said the one thing nobody had said to me in longer than I could remember, that I didn&apos;t have to be useful today. I sat with that for a while before I even opened the picnic. That night the table was set right there in the sand, no walls, just the ocean going dark and quiet beside me, and I ate slowly, the way you eat when nobody is waiting for you to finish.</span></aside>
        </section>

        <figure className="restoration-image"><img src="/journeys/ex6/exhausted-singita-sasakwa.jpg" alt="The Serengeti plains seen from Singita Sasakwa Lodge" /><figcaption>Serengeti · Tanzania</figcaption></figure>

        <section className="restoration-phase">
          <header><p>Phase Two</p><h2>Awaken</h2><span>Nights 5 – 7 · Serengeti</span><strong>Singita Sasakwa Lodge <em>· ultra-luxury, Grumeti Reserve</em></strong></header>
          <article className="restoration-day"><p className="day-number">Day Five</p><h3>The Plains Open</h3><small>Staying: Singita Sasakwa Lodge, Grumeti Reserve</small><p>From the air, the coast disappeared and the plains just kept going, no fences, no edges, grass the colour of old gold running out to a horizon that never seemed to arrive. My guide was leaning against the Land Rover when we landed, a Maasai tracker beside him already scanning the tree line out of habit. We didn&apos;t rush the drive. He stopped for a lilac-breasted roller sitting on a fence post like it was the most important thing in Tanzania, and for a while, it was. We ended the day at a kopje, drinks in hand, watching the light go from white to gold to almost nothing, and dinner that night was under more stars than I knew existed.</p></article>
          <article className="restoration-day"><p className="day-number">Day Six</p><h3>Above the Earth</h3><p>Someone knocked before it was properly light out. There was nothing about this on the paper they&apos;d handed me on Day One.</p></article>
          <aside className="restoration-surprise"><p>The Ryravel Surprise · Not disclosed in advance</p><span>The balloon lifted off while the plains were still grey, and then the sun came up over the far tree line and turned everything underneath us gold at once, wildebeest strung out for miles like a river that had decided to walk instead of flow. Nobody in the basket said much. What was there to say. We came down in tall grass and there was a table already laid in the middle of nowhere, white cloth, champagne going warm faster than we could drink it, and I remember laughing for no reason with people I&apos;d met four days earlier. I hadn&apos;t laughed like that in longer than I wanted to admit.</span></aside>
          <article className="restoration-day"><p className="day-number">Day Seven</p><h3>The Last Morning Wild</h3><p>My guide took the long way for the last drive, in no hurry to hand me back to the road. We found a leopard draped over a branch, half-asleep, entirely uninterested in us, and sat with her for twenty minutes without either of us saying it was time to go. Eventually it was.</p></article>
          <aside className="restoration-signature"><p>Ryravel Signature · The Photoshoot · Day 7</p><h3>Not a tourist photo. Something closer to proof.</h3><span>A woman with a camera was waiting where the drive ended, and she didn&apos;t ask me to pose so much as she asked me to stand still and let the light do what it was already doing. Forty minutes, maybe less. I forgot the camera was there for most of it. The pictures reached me three days after I was home, unpacked, back in my own kitchen, and the person in them stood differently than I remembered standing. Looser in the shoulders. I kept one on my desk.</span></aside>
        </section>

        <figure className="restoration-image"><img src="/journeys/ex6/exhausted-ngorongoro-aerial.jpg" alt="An aerial view of a lodge within the green Ngorongoro landscape" /><figcaption>Ngorongoro · Tanzania</figcaption></figure>

        <section className="restoration-phase">
          <header><p>Phase Three</p><h2>Descend</h2><span>Nights 8 – 10 · Ngorongoro Crater</span><strong>Entamanu Ngorongoro <em>or Ngorongoro Lions Paw · intimate rim camps</em></strong></header>
          <article className="restoration-day"><p className="day-number">Day Eight</p><h3>Into the Crater</h3><small>Staying: Entamanu Ngorongoro / Ngorongoro Lions Paw, crater rim</small><p>I walked into the room and stopped in the doorway, because the whole crater was just there, six hundred metres down, laid out like something that shouldn&apos;t fit inside a single view. I didn&apos;t do much that afternoon. Sat on the edge of the bed and looked at it, mostly. Dinner was candlelit on the rim, and somewhere between the second course and the third, the sky went properly dark and the Milky Way showed up like it had never once considered not showing up.</p></article>
          <article className="restoration-day"><p className="day-number">Day Nine</p><h3>The World&apos;s Largest Eden</h3><p>The road down into the crater switches back on itself so many times you lose the rim behind you before you&apos;ve properly left it. Down on the floor, everything was closer than I expected, hippos wallowing loud enough to hear before we saw them, flamingos standing in a lake the colour of weak tea, a pair of lions who couldn&apos;t be bothered to lift their heads as we passed. We ate lunch parked by the hippo pool, sandwiches balanced on our knees, nobody in any hurry to move on. By the time we climbed back to the rim the light had turned the whole crater the colour of the inside of a shell, and dinner that night took almost three hours, and not once did it feel long.</p></article>
          <article className="restoration-day"><p className="day-number">Day Ten</p><h3>The Maasai Morning</h3><p>We sat on stools too low for me in an elder&apos;s home that wasn&apos;t built for anyone&apos;s benefit but his family&apos;s, and his youngest daughter, maybe ten, kept sneaking looks at me while she practiced her English. She wanted to know if my city had cows. I told her no, and she looked genuinely sorry for me. Tea, then goodbyes, then a short flight back toward the coast, forty minutes in the air that somehow covered a lot more ground than that.</p></article>
        </section>

        <blockquote>“You do not go from the crater to a departure gate. The coast is where the arc completes.”</blockquote>

        <section className="restoration-phase">
          <header><p>Phase Four</p><h2>Close &amp; Carry</h2><span>Nights 11 – 12 · Zanzibar</span><strong>Zuri Zanzibar <em>· return stay, Kendwa Beach</em></strong></header>
          <article className="restoration-day"><p className="day-number">Day Eleven</p><h3>Integration</h3><small>Staying: Zuri Zanzibar, Kendwa Beach</small><p>Two hours on the table, the longest treatment of the whole trip, and I remember thinking partway through that I couldn&apos;t tell anymore where the massage ended and the sound of the ocean began. Afterward I wandered without a destination, bought a small carving from a man who&apos;d made it that week, sat in the shade until the shade moved and I had to move with it. Dinner that evening had the shape of a celebration without anyone announcing it as one. My host lifted a glass, said something short and warm, and then left us to it, which was its own kind of gift. A journal was sitting at my place when I got back to the table. I didn&apos;t open it that night. I wanted to write in it slowly, later, when I had something worth putting down.</p></article>
          <article className="restoration-day"><p className="day-number">Day Twelve</p><h3>Late Checkout. The Return Begins.</h3><p>I ate breakfast without once looking for a clock, which by then had stopped feeling unusual and started feeling like how mornings should go. Checkout wasn&apos;t until one, so I didn&apos;t rush the last of the coffee. A box was placed in my hands before the driver took my bags, and I held onto it the whole ride to the airport like it might slip away from me if I let go. Cold water in the car. Flowers I hadn&apos;t asked for. A letter I decided, without quite deciding, to save for the plane.</p></article>
          <aside className="restoration-signature"><p>Ryravel Signature · The Departure Box · Day 12</p><h3>What I actually carried home.</h3><span>I opened the letter somewhere over open water, and I won&apos;t say what it held, that part was mine. What I can tell you is that I sat with it in my lap for a long time after I&apos;d finished reading, not sad exactly, just full in a way I hadn&apos;t been in years. There&apos;s a version of me that flew into Zanzibar twelve days earlier bracing for the next thing before the current one had even landed. She didn&apos;t get on the flight home. I don&apos;t know exactly when I put her down, somewhere between the balloon and the crater and that basket on the sand, but she stayed behind, and I noticed the absence of her the way you notice a held breath finally leaving your chest. I didn&apos;t feel like I was returning to my life. I felt like I was bringing someone steadier back to meet it.</span></aside>
        </section>
      </div>

      <section className="restoration-hotels"><div><p className="section-label">Where You Stay</p><h2>Four properties. Three landscapes. One arc.</h2><div className="restoration-hotel-grid">
        <article><span>Zanzibar · Coast</span><h3>Baraza Resort &amp; Spa</h3><em>Spa-first · Bwejuu Beach</em><strong>Nights 1–4</strong></article>
        <article><span>Serengeti · Plains</span><h3>Singita Sasakwa Lodge</h3><em>Ultra-luxury · Grumeti Reserve</em><strong>Nights 5–7</strong></article>
        <article><span>Ngorongoro · Crater</span><h3>Entamanu Ngorongoro / Ngorongoro Lions Paw</h3><em>Intimate rim camp · crater views</em><strong>Nights 8–10</strong></article>
        <article><span>Zanzibar · Coast</span><h3>Zuri Zanzibar</h3><em>Boutique · Kendwa Beach</em><strong>Nights 11–12</strong></article>
      </div></div></section>

      <section className="restoration-dates"><div><p className="section-label">Travel Dates</p><h2>When would you begin?</h2><p>This journey runs year-round. Pricing shifts by season, not by experience quality, so tell us your preferred window and we&apos;ll confirm exact rim, camp, and villa availability before anything is booked.</p><form action="/request" method="get"><label>Preferred start date<input type="date" name="start-date" /></label><label>Travelling as<select name="party" defaultValue="2 people sharing"><option>2 people sharing</option><option>Solo traveller</option><option>3–4 people</option><option>5+ people</option></select></label><input type="hidden" name="journey" value="Exhausted, The Restoration" /><button type="submit">Check availability</button></form><p className="restoration-seasons"><b>High</b>, July, August, September, October &nbsp;&nbsp; <b>Shoulder</b>, January, February, June, November, December &nbsp;&nbsp; <b>Low / Green</b>, March, April, May</p></div></section>

      <section className="restoration-price"><div><div><p className="section-label">Investment</p><h2>Eleven nights. Three worlds. The complete arc.</h2><p>International flights not included. All internal flights between Zanzibar, Serengeti, Ngorongoro and back, all transfers, experiences, meals where indicated, Signature Rituals, and Ryravel host support are included.</p></div><div><small>From</small><strong>$43,500</strong><span>per person · prices vary by season</span><Link className="button button-red" href="/request?journey=Exhausted%2C%20The%20Restoration">Begin the conversation →</Link><Link className="button button-outline-dark" href="/journeys">All journeys</Link></div></div></section>

      <section className="restoration-months"><div><p className="section-label">Prices by Month</p><h2>Exhausted, The Restoration · 11 Nights · Zanzibar + Serengeti + Ngorongoro</h2><p>International flights are not included. Prices are per person based on two people sharing. All 12 months are available. Prices vary by season, not by experience quality.</p><div className="restoration-month-grid">{months.map(([month, season]) => <article className={season} key={month}><span>{month}</span></article>)}</div><p className="restoration-month-legend">High &nbsp;July · August · September · October&nbsp;&nbsp;&nbsp; Shoulder &nbsp;January · February · June · November · December&nbsp;&nbsp;&nbsp; Low &nbsp;March · April · May</p></div></section>

      <section className="restoration-closing"><Link href="/journeys">← Back to all journeys</Link><p>&quot;You arrive heavy with everything your life has asked of you.<br />Tanzania asks nothing. It only gives.&quot;</p><span>, Ryravel · Stillness is the only luxury left.</span></section>
    </main>
  );
}
