import Link from "next/link";
import styles from "./KimbilioJourney.module.css";
import JourneyTrustLayer, { JourneyPricingNote } from "../../components/JourneyTrustLayer";
import { JourneyAvailability, JourneyFaqs } from "./JourneyPlanning";

const days = [
  { label: "Day 01", title: "The World Falls Away", route: "Southern Serengeti Lodge · Night 1", paragraphs: ["The charter in was the first time in weeks I hadn't had a screen open in front of me, and I noticed how unfamiliar that felt more than I noticed the landscape. The lodge was the last real bed I'd have for a while, and I slept in it without knowing that yet. That afternoon's drive put more life in front of me at once than I think I'd registered in months, calves everywhere, the plains loud with something I didn't have a name for. My guide mentioned there was Wi-Fi that night, the last of it for a stretch, and suggested I leave it alone. I did, and felt a small, specific relief at not even having the option anymore."] },
  { label: "Day 02", title: "The Serengeti Opens", route: "Southern Serengeti Lodge · Night 2", paragraphs: ["A dawn drive found a cheetah stalking something I never saw the outcome of, and I found myself oddly at peace not knowing how it ended, which isn't like me at all, I usually need the ending. We rested through the heat, then walked the southern plains with a tracker who read the ground like it was still saying something to him personally. That evening my guide asked me, plainly, what I was actually hoping this trip would do to me. I didn't have a real answer. I said something vague about needing space. He just nodded, like he'd expected that, and let it go."] },
  { label: "Days 03 & 04", title: "Into the Calving, Hunt, Birth, Survival", route: "Ndutu Mobile Luxury Camp · Nights 3–4", paragraphs: ["We arrived to lions working the edge of a herd like it was any other Tuesday for them, and something about the total absence of drama in how they went about it stuck with me longer than the kill itself did. Day Four started before light, and the calving and the hunting ran together the whole morning, birth and death close enough to overlap, neither one apologizing for the other. In the afternoon I walked the plains instead of driving them, and by the fire that night my guide asked what the day had actually changed in how I understood something. I said I wasn't sure yet. He said that was usually the honest answer on Day Four."] },
  { label: "Day 05", title: "The Migration in Golden Light", route: "Ndutu Mobile Luxury Camp · Night 5", paragraphs: ["I didn't know what was coming today. Nobody had told me to expect anything at all. A woman with a camera met us on the plains at golden hour, the herd moving somewhere behind me the whole time. She didn't direct much, just let me stand there while the light did most of the work. Forty-five minutes, maybe more. I forgot she was there for long stretches of it. The pictures reached me three days after I was home, and I sat with them longer than I expected to, mostly because the person in them didn't look like someone going through the motions of anything.", "Back at camp, a basket was waiting, a kaftan, something carefully arranged, a note that read I'd come here to disappear and was starting to be found. I sat with it longer than I expected to, because it named something I hadn't said out loud to anyone, not even myself, that disappearing had been the actual plan when I booked this. Tomorrow, I was told, the arc goes off-grid properly. Tonight felt like the last soft thing before it did."] },
  { label: "Day 06", title: "The Last Step Away", route: "Ndutu Fly Camp · Night 6", paragraphs: ["A short drive, then a walk in, the shift from the mobile camp's comfort to something much plainer was deliberate and I felt it land as soon as I ducked into the tent. We walked the perimeter before dark. The herd was audible from where I sat, not visible exactly, just present, a low constant sound I stopped noticing as separate from my own breathing by the second hour. Dinner was off the fire. No generator meant the dark stayed properly dark, and the calving season kept going somewhere out there in it, whether or not I was watching."] },
  { label: "Day 07", title: "Walking into the Birth", route: "Ndutu Fly Camp · Night 7", paragraphs: ["Nothing about this morning had been written down for me anywhere. My guide came to the tent before five and walked me out on foot to a spot no vehicle could have reached. I stood in the middle of the herd while calves were being born within metres of me, and none of them registered me as anything worth reacting to. Thirty minutes, no instruction to do anything at all. I've spent a long time watching my own life from somewhere just outside it. Standing there, nothing between me and it happening, I wasn't watching anything. I was just there, the same as everything else that was there. We walked back for a bush breakfast, and I didn't want to talk for most of it. The last fire that evening, my guide sat with me and didn't speak unless I did first."] },
  { label: "Day 08", title: "The Crater. Ancient World.", route: "Ngorongoro Crater Rim · Night 8", paragraphs: ["The caldera opened up beneath the plane like something that had been waiting there the entire time I was elsewhere. Rim check-in, rest, the view doing most of the work that afternoon. Dinner was candlelit on the rim, and somewhere in it I noticed the thought of going home didn't land in my chest the way it had a week ago, like something being taken from me. It landed more like something I might actually be ready to walk back into."] },
  { label: "Day 09", title: "Into the Caldera", route: "Ngorongoro Crater Rim · Night 9", paragraphs: ["A full day down on the crater floor, 25,000 animals in a bowl about 260 square kilometres in area, and my guide never once tried to hurry any of it. Lunch was by a hippo pool, and we kept going as long as I wanted to, climbing back up only once I said so myself. Dinner on the rim that night was slow in a way that used to make me restless and didn't anymore."] },
  { label: "Day 10", title: "The Maasai Morning. The Return.", route: "Ngorongoro · Departure", paragraphs: ["We visited a single elder's family that morning, tea, unhurried conversation at a pace that had nothing to do with any schedule I was carrying. Before I left, the box was presented, Maasai beadwork inside it, a pressed wildflower from the calving grounds, oils pressed locally, and a handwritten note from my guide about what he'd noticed in me over nine nights, things I hadn't said out loud that he'd apparently been watching anyway. I read his note twice before I opened the sealed letter underneath it. What that one said is mine to keep. What I'll say is that nine nights ago I couldn't have told you what I was hoping this trip would do to me. By the time I opened that letter, I didn't need to ask anymore. The drive to the airport was quiet, and I held it all on my lap the whole way, nine nights, the walk into the calving grounds, the crater, the tea with strangers who felt oddly less like strangers by the end, all of it somehow sealed inside something I could actually hold."] },
];

function Day({ day }) {
  return <article className={styles.day}><div className={styles.dayMeta}><span>{day.label}</span><h3>{day.title}</h3><small>{day.route}</small></div><div className={styles.dayCopy}>{day.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></article>;
}

export default function FullCalvingArcJourney({ journey }) {
  const requestHref = `/request?journey=${journey.slug}&name=${encodeURIComponent(journey.title)}&destination=${encodeURIComponent(journey.destination)}&nights=${journey.nights}&price=${encodeURIComponent(journey.price)}`;
  const callHref = `${requestHref}&conversation=private-call`;

  return <main className={`${styles.page} ${styles.fullCalvingArc}`}>
    <section className={styles.hero}><img src={journey.image} alt={journey.imageAlt} width="1920" height="1280" fetchPriority="high" /><div className={styles.heroShade} aria-hidden="true" /><div className={styles.heroTop}><Link href="/journeys/disconnected">← Disconnected · The Return</Link><span>Spiritual homecoming</span></div><div className={styles.heroBody}><p className={styles.eyebrow}>The Full Calving Arc · January to March</p><h1>The Full Calving Arc</h1><p className={styles.meaning}>Southern Serengeti Lodge · Ndutu Mobile · Fly Camp · Ngorongoro</p><h2>From watching life<br />to being part of it.</h2></div><dl className={styles.facts}><div><dt>Duration</dt><dd>9 Nights, 10 Days</dd></div><div><dt>Season</dt><dd>January–March · Calving Plains</dd></div><div><dt>From</dt><dd>$15,377 / person</dd></div></dl></section>

    <section className={styles.opening}><div className={styles.openingMain}><span className={styles.sectionLabel}>Why this journey</span><h2>Four settings.<br />A gradual return to participation.</h2><div className={styles.openingCopy}><p>I've been going through the motions of my own life for a while now, showing up to it the way you show up to a meeting you didn't need to be in. I can't point to the day it started. I just know I'd stopped feeling like a participant in anything, including my own house.</p><p>Nine nights, four settings, each one stripping something further back. A lodge to land softly in. A mobile camp on the calving grounds where nothing about birth and death out there is dressed up for visitors. A fly camp with no generator and no walls. Then the crater, where I was supposed to come back down, gently, into something that still felt like mine.</p></div></div><aside className={styles.openingAside}><span>In one sentence</span><p>Not simply a safari. A way back inside your own life.</p></aside></section>

    <section className={styles.fit}><div><span className={styles.sectionLabel}>Who this is for</span><h2>Showing up.<br />Not quite there.</h2></div><div><p>The Full Calving Arc is designed for someone who wants enough time for the transition to feel real: a soft landing, close immersion, a deliberate step off-grid and a human return.</p><ul><li>You want the calving season without a sightings checklist.</li><li>You are open to two simple fly-camp nights after the comfort of the lodge and mobile camp.</li><li>You want Ngorongoro to close the journey, not merely extend it.</li></ul><Link href={requestHref}>Ask a curator about The Full Calving Arc →</Link></div></section>

    <section className={styles.itinerary} aria-labelledby="full-calving-arc-itinerary"><header><span className={styles.sectionLabel}>The journey · Phase One · Land &amp; Open</span><h2 id="full-calving-arc-itinerary">Ten days of<br /><em>coming back into life.</em></h2><p>Nights 1–2 · Southern Serengeti · Lodge</p></header>
      {days.slice(0, 2).map((day) => <Day day={day} key={day.label} />)}
      <section className={styles.signature}><span>Phase Two · Nights 3–5 · Ndutu Mobile Luxury Camp</span><h2>Ndutu Immersion.</h2><p>The camp sits right on the calving grounds, close enough that the drama of birth and predation isn't scenery, it's the neighborhood. No Wi-Fi. Lake Ndutu visible from the fire.</p></section>
      {days.slice(2, 4).map((day) => <Day day={day} key={day.label} />)}
      <figure className={styles.landscape}><img src="/journeys/full-calving-arc/guided-plains-walk.webp" alt="Traveller and guides walking together through dry grass on open plains" width="1920" height="1280" loading="lazy" /><figcaption>A guided walk on the plains · the landscape at human pace.</figcaption></figure>
      <section className={styles.signature}><span>Phase Three · Nights 6–7 · Ndutu Fly Camp</span><h2>Off the Grid.</h2><p>A temporary structure, a cook fire, a long-drop, my guide. No generator after nine. No Wi-Fi. The calving grounds are the immediate environment, not a view of them.</p></section>
      {days.slice(4, 6).map((day) => <Day day={day} key={day.label} />)}
      <blockquote className={styles.pullQuote}>“On foot inside the herd, I stopped being a visitor. I became something the ecosystem simply had to account for.”</blockquote>
      <section className={styles.signature}><span>Phase Four · Nights 8–9 · Ngorongoro Crater</span><h2>Descend &amp; Reconnect.</h2><p>Two nights at the crater create space to return gradually, before Day 10 brings the journey home.</p></section>
      {days.slice(6).map((day) => <Day day={day} key={day.label} />)}
    </section>

    <section className={styles.season}><div><span className={styles.sectionLabel}>The calving window</span><h2>January through March.</h2><p>February is the peak calving period in this journey design. Wildlife movement, available camps and departure pricing are confirmed for your dates; no particular sighting can be promised.</p></div><div className={styles.months} aria-label="The Full Calving Arc travel window">{["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"].map((month, index) => <span className={index < 3 ? styles.openMonth : ""} key={month}>{month}</span>)}<p className={styles.monthLegend}><b>Open</b> January, February and March<br />March departures from $15,377 per person</p></div></section>
    <JourneyAvailability journey={journey} title="When would you come back into the moment?" copy="Share your preferred dates and party. We will confirm the lodge, mobile camp, fly camp, internal flights and exact investment personally." openMonths={journey.availableMonths} closedNote="This calving-season edition is available January through March only." />
<section className={styles.investment}><div><span className={styles.sectionLabel}>Investment</span><h2>Nine nights.<br /><em>Lodge to fly camp to crater.</em><br />Inclusions, clearly stated.</h2></div><div className={styles.price}><small>From · March departures</small><strong>$15,377</strong><span>/ person</span><JourneyPricingNote /><p>International flights not included. Available January through March only. All internal flights, all accommodation, full-day crater descent, the Maasai enkiama visit, Signature Rituals, and Ryravel host support are included. February is peak calving, the highest birth and predator density. Exact arrangements and departure price are confirmed in your personal proposal.</p><div className={styles.priceActions}><Link href={requestHref}>Begin the conversation →</Link><Link className={styles.secondaryAction} href={callHref}>Request a private call</Link></div><small className={styles.reassurance}>A curator responds personally within one business day. Nothing is booked until you are ready.</small></div></section>
    <JourneyTrustLayer />
    <JourneyFaqs journey={journey} />
    <section className={styles.nextSteps}><div><span className={styles.sectionLabel}>What happens next</span><h2>A private conversation.<br />Then the full arc.</h2></div><ol><li><span>01</span><div><h3>Tell us what drew you here</h3><p>Share your dates, party and the pace you need.</p></div></li><li><span>02</span><div><h3>Speak with your curator</h3><p>We explain the fly-camp facilities and confirm each setting for your departure.</p></div></li><li><span>03</span><div><h3>Receive a considered direction</h3><p>One personal proposal, with no booking until you are ready.</p></div></li></ol><Link href={requestHref}>Plan The Full Calving Arc privately →</Link></section>
    <section className={styles.closing}><div className={styles.backLinks}><Link href="/journeys">← Back to all journeys</Link><Link href="/journeys/disconnected">Disconnected · The Return</Link></div><blockquote>“I came here disconnected from everything that mattered.<br />Standing inside the herd, I remembered what being part of something actually feels like.”</blockquote><p>Ryravel · The Full Calving Arc</p></section>
  </main>;
}
